-- AUTOMATICALLY GENERATED BY <C:\Users\Public\Games\World of Warcraft\Interface\AddOns\_NPCScan.Tools\Update\objs_to_overlays.pyc>!
select( 2, ... ).PathData = {
	[ 465 ] = { -- Hellfire Peninsula
		-- Mekthorg the Wild
		[ 18677 ] = "ie³Fhü·´k=´zhü·´jŸ¸>k=´zk=´zoO¢aie³Fk‹¢‚ie³FoO¢ar&ž±k‹¢‚oO¢apH—yk‹¢‚r&ž±pH—yr&ž±vÜœÙuÜ•ÏpH—yvÜœÙuÜ•ÏvÜœÙ{\8’½zû‰\15uÜ•Ï{\8’½zû‰\15{\8’½\127\6‰k\127\6‰kz’„ãzû‰\15ƒ‡´z’„ã\127\6‰kƒ‡´~\\~žz’„ã|¿}\"z’„ã~\\~žvxrz’„ã|¿}\"w§k˜vxr|¿}\"w§k˜rÊs\11vxrrÊs\11sTu2vxrqœmcrÊs\11w§k˜w§k˜snh1qœmcv\17h>snh1w§k˜~\\~žƒ‡´Š~ÙŠ~Ùƒ‡´Ž;‚nru”ÏpH—yuÜ•Ï°½½\7£¯µR¢ä½Ù°½½\7¢ä½Ù¤LÀu°½½\7¤LÀu®pÆy®pÆy¤LÀu¬\"Çè¥»²•£¯µR°½½\7¥»²•°½½\7²Ýº\28²Ýº\28¯¾®U¥»²•±Ñ¯.¯¾®U²Ýº\28±Ñ¯.²Ýº\28¶öµµ¶öµµ²Ýº\28·\16¹J";
		-- Fulgorge
		[ 18678 ] = "?;u÷:0“@B‰x´B‰x´:0“@>\14“g>\14“g:0“@@!¤É@!¤É:0“@<q¦>?;u÷B‰x´G€o·E›k\21?;u÷G€o·E›k\21G€o·NÅhlL\14eSE›k\21NÅhlL\14eSNÅhlQ£ZkN}Y\127L\14eSQ£ZkFÜ©ŒFL²\12IÛ±‚FÜ©ŒIÛ±‚J…ª…Mc¥µFÜ©ŒJ…ª…Jº¢¯FÜ©ŒMc¥µJº¢¯Mc¥µQÞŸùQ:™ûJº¢¯QÞŸùQ:™ûQÞŸùV?™ÍV?™ÍQÞŸùW\30ŸåV?™ÍW\30ŸåYîšÚX1“tV?™ÍYîšÚX1“tYîšÚ[6‘ÿY“Š\15X1“t[6‘ÿY“Š\15[6‘ÿ]I‹ç\\à„ãY“Š\15]I‹ç\\à„ã]I‹çcþ†Üc&€–\\à„ãcþ†Üc&€–cþ†ÜkJ€ËkJ€Ëcþ†Ül\"†8kJ€Ël\"†8r3ƒ\5p£}ókJ€Ër3ƒ\5p£}ór3ƒ\5u”~žs¶z~p£}óu”~žfs¥¨j6´gjd¥Èfs¥¨f®¸Áj6´gj6´gf®¸Ám/¶1f®¸Ál\8»‹m/¶1m/¶1l\8»‹qø¹\22u¨¶Ym/¶1qø¹\22t¢¯±m/¶1u¨¶YzÔ¯åt¢¯±u¨¶YzÔ¯åu¨¶Yz^¶_zÔ¯åz^¶_²µ\4²µ\4z^¶_Ìºk—\16´µ²µ\4Ìºk—º\28—\16´µÌºk";
		-- Vorakem Doomspeaker
		[ 18679 ] = "‡üC¯†lFEˆ\16M\1˜ÁL]‡üC¯ˆ\16M\1˜ÁL]ˆ\16M\1¤RÑ˜ÁL]¤RÑ§üRaŸKÓ˜ÁL]§üRa¥LH­ŸKÓ§üRa§üRa©áO—¥LH­¨áJD¥LH­©áO—°ëov¯Nr°³ãoØ¯Nr°²ax\9³ãoØ³ãoØ²ax\9¶syX³ãoØ¶syX¹õw1¹Jg¡³ãoØ¹õw1¹Jg¡¹õw1¿'gKº¦aë¹Jg¡¿'gKº¦aë¿'gK¿Ëao½\14^žº¦aë¿Ëaoµ\17ˆ§³¯ùº=‰Àº=‰À³¯ù¾\13’ë³¯ù¸7š™¾\13’ë¾\13’ë¸7š™¾!˜Î¾!˜Î¸7š™º³œ²cK\8a'Nžc©T@cK\8c©T@jkUÂk\8IXcK\8jkUÂo.L²k\8IXjkUÂo.L²jkUÂmžTM";
	};
	[ 467 ] = { -- Zangarmarsh
		-- Marticar
		[ 18680 ] = "\29˜€Ñ\25º}ó\23ÜŠJ\29˜€Ñ\23ÜŠJ\28W‰D\23ÜŠJ\25K²\28W‰D\28W‰D\25K²\30ú\27\25K²\28à‘·\30ú\27\25º}ó\29˜€Ñ HxÕ\28Æu8\25º}ó HxÕ\28Æu8 HxÕ&ör@$\5n\20\28Æu8&ör@$\5n\20&ör@+qab(K]I$\5n\20+qab(K]I+qab/¸[C+îW€(K]I/¸[C+îW€/¸[C0¤M‹,ÍLí+îW€0¤M‹caS‚^\\]BeSZ\2eSZ\2^\\]Bb©^„^\\]B^Ìfšb©^„b©^„^ÌfšbÞf_caS‚eSZ\2quT÷quT÷eSZ\2r@[6quT÷r@[6}(Q\6{àK¹quT÷}(Q\6{àK¹}(Q\6\127!L\8\127!L\8}(Q\6ŽÙU9}(Q\6jZÀŽÙU9µÂYK°h`¾¶ö^ó¶ö^ó°h`¾µ\17a½°h`¾´ðe›µ\17a½°h`¾°øg“´ðe›´ðe›°øg“¿Ñu\30°øg“¼ÌxD¿Ñu\30¿Ñu\30¼ÌxDÌ\27ŠÔ¼ÌxDÉQŽBÌ\27ŠÔºJYeµÂYK¶ö^óºJYe¶ö^ó¹\127^ÒºJYe¹\127^Ò¿i\\V¹\127^Ò¾.aª¿i\\V";
		-- Coilfang Emissary
		[ 18681 ] = "A\6\\V?!^ùCg]æCg]æ?!^ùEãxïA‰yÇEãxï?!^ùEãxïA‰yÇDZ{)˜\29\\˜—“`\6™Wb\5š\22[J˜\29\\˜™Wb\5¢Ý_\\š\22[J™Wb\5™Wb\5 Äe\4¢Ý_\\¢Ý_\\ Äe\4§€i†§€i† Äe\4¢{jq¢{jq¥\30tS§€i†¢{jq °q&¥\30tS¡&uz¥\30tS °q&¥\30tS¡&uz£ˆv8¶»¶§´\4·­²9ºÚº˜Ä”¶»¶§²9ºÚ²9ºÚ¸ÎÅéº˜Ä”¿ØÂM½ÙÅ_Á©Å%½ÙÅ_¿ÞÇõÁ©Å%§“±ñ¢M¥€O²3O²3¦\30´Ž§“±ñ¦\30´ŽO²3žØµ\17¤›¥Ï¢M¥€§“±ñ¼<Ï'¹õÒ¾UÒg¹õÒ¼cÕÂ¾UÒg";
		-- Bog Lurker
		[ 18682 ] = "lP—d™ûbä5lP—bä5i^¢i^¢bä5cÝ¢@cÝ¢@i\22«/i^¢cÝ¢@f”¬/i\22«/d™ûlP—lw”9lw”9lP—p\13šClw”9p\13šC\127\26“•p\13šC~\13™\22\127\26“•„›˜>\127\26“•~\13™\22„›˜>~\13™\22\127åš…„›˜>\127åš…„µÌ\127åš…€Nž¤„µÌ€Nž¤‚\31¦+„µÌ€Nž¤\127\0¥s‚\31¦+\127\0¥s~Å¬V‚\31¦+~Å¬Vœ­\20‚\31¦+Ö$ÌíÒ@ÆÑnË\1Ö$ÌíÑnË\1Ó2ÍìÖÁÄ‡Ò@ÆÖ$ÌíÛwÈ\127ÖÁÄ‡Ö$ÌíÖ$ÌíÙ\9Ï|ÛwÈ\127ÛwÈ\127Ù\9Ï|ß Ñ\12Ù\9Ï|Ú³Óêß Ñ\12Ú³ÓêÝÌÜÙß Ñ\12Ú³ÓêÚ\"Ü(ÝÌÜÙÚ\"Ü(Ú‹ì„ÝÌÜÙÝÌÜÙÚ‹ì„Þ\26ì\1:á@\0267$9õ6SF”:á@\0266SF”: EÝ: EÝ6SF”8M\27?;Gl: EÝ8M\27?;Gl8M\27@NNi?;Gl@NNiDˆLÆ?;GlDˆLÆFãI™BD¯?;GlFãI™Dñ>BBD¯FãI™Dñ>BFãI™JŒ<\1D,:áDñ>BJŒ<\1IÔ5ŽD,:áJŒ<\1Eã3\18D,:áIÔ5Ž@‰9\9D,:áEã3\18@ª2‚@‰9\9Eã3\18:74\18@‰9\9@ª2‚:74\18<˜;~@‰9\9:74\0187$9õ<˜;~7$9õ:á@\26<˜;~";
	};
	[ 473 ] = { -- Shadowmoon Valley
		-- Collidus the Warp-Watcher
		[ 18694 ] = "™x43“Ã7l™õ8K“Ã7l”¼;‹™õ8K¢¢4n™x43™õ8K¢¢4n™õ8K¢38e¢¢4n¢38eª’:r¢¢4nª’:r¬\"6f¬\"6fª’:r­58è­58èª’:r®'H“®'H“ª’:r«¹L¥®'H“«¹L¥½—LC®'H“½—LC¾ùH\29¾ùH\29½—LCÀuJ\9ÀuJ\9½—LCÁøV¨½—LC¿HW$ÁøV¨_i³]Vjq[…o¾a·u\11_i³[…o¾[‹u¡a·u\11[…o¾a·u\11[‹u¡]«x1i\127l˜_i³a·u\11i\127l˜a·u\11mŠqAmŠqAa·u\11gÈxâgÈxâl6}5mŠqAmŠqAl6}5uý‚£l6}5o—†µuý‚£uý‚£o—†µw\3‰*w\3‰*o—†µu\11Š³Ž¾¯ì‹à°‰4µm‹à°‰Œ<¶\304µm4µmŒ<¶\30Ø»‘Œ<¶\30Ž!¾ËØ»‘Ø»‘Ž!¾Ë‘ëÃˆ–\23½\20Ø»‘‘ëÃˆ“¶º¦Ø»‘–\23½\20í­i“¶º¦–\23½\20“¶º¦í­iœPª=œPª=í­i¢\18ª^¢\18ª^í­iž}¯Ñ¥8¬„¢\18ª^ž}¯Ñž}¯Ñ¢\5³g¥8¬„«¥µ\
¥8¬„¢\5³gª³­.¥8¬„«¥µ\
ª³­.«¥µ\
¶y°\26µz¬\1ª³­.¶y°\26 u¦®œPª=¢\18ª^O¦YœPª= u¦®¢,ž«O¦Y u¦®¢,ž«Ÿv\7O¦Y";
		-- Ambassador Jerrikar
		[ 18695 ] = "HÕy­F?z¬J\22\127UF?z¬Gs‚:J\22\127UJ\22\127UGs‚:LÆƒÝLÆƒÝGs‚:Iº…®LÆƒÝIº…®LôŽùIº…®IÁ‘ LôŽùLôŽùIÁ‘ P\0•zIÁ‘ Mæ˜\16P\0•zwšQ½qœK^pùPbwšQ½pùPbtgSaqœK^wšQ½yŒD›yŒD›uYAAqœK^wsAhuYAAyŒD›˜´_ìŒ]\\úŒ\27_'Œ\27_'ƒdþ˜´_ì˜´_ìƒdþ’\12f‘\25W\3Œ]\\ú˜´_ì‘\25W\3˜´_ì™0YÔy=¤‡qÄ¬í|~®ì|~®ìqÄ¬íqø°4xe¸´|~®ìqø°4zî·â|~®ìxe¸´{˜¤µy=¤‡|~®ì²\25–L®B—Õ¬¥\7¸üš^²\25–L¬¥\7¬¥\7­I¡©¸üš^¸üš^­I¡©ºd„ºd„­I¡©°u¥2°u¥2¸õ¨ººd„ºd„¸õ¨ººÚ§";
		-- Kraator
		[ 18696 ] = "e¼fÈe›i†j\15m\7e¼fÈj\15m\7o·cZj\15m\7oOn\20o·cZj¬a e¼fÈo·cZm}¨Œi†¬²rÐªWrÐªWi†¬²oŠ·Îi†¬²i³µRoŠ·Îqÿ§Km}¨ŒrÐªW—lq •%y*œžruœžru•%y*«yX•%y*–+\127H«yX–+\127H˜*€Ø«yXr\5\28qp\30\27v”\29„v”\29„p\30\27x\9 4p\30\27q-%?x\9 4q-%?w€(ex\9 4T•rML/m5L\8rGT•rML\8rGN‘v®T•rMN‘v®SñvESñvEN‘v®Qby\22O±kÚL/m5T•rM";
	};
	[ 475 ] = { -- Blade's Edge Mountains
		-- Morcrush
		[ 18690 ] = "Ÿ\6=Æ˜r7Â–>;\8Ÿ\6=Æ–>;\8›ÓA\12–A:›ÓA\12–>;\8›ÓA\12–A:™™C½˜r7ÂŸ\6=Æ ò9lŸ3Z˜r7Â ò9lœô1–˜r7ÂŸ3Z­I¢•ªÚ¥È¯ò¤ã¯ò¤ãªÚ¥È²\18¾U²\18¾UªÚ¥È­\14¿[²\18¾U­\14¿[¯åÁa±hS@­óMæ­ÒUã±hS@­ÒUã±Xü±hS@±XüÀUÖ¿òPb±hS@ÀUÖ±[PU­óMæ±hS@¯ÑKk­óMæ±[PU¯ÑKk±[PU½!L]»6Fé¯ÑKk½!L]½!L]Á@?5»6Fé¿±9Q»6FéÁ@?5Åš9è¿±9QÁ@?5Åš9èÁ@?5ÄÜ?ÊÓ@|Åš9èÄÜ?ÊÓ@|ÄÜ?Ç*BñÇ*BñÊJO¤ÊÓ@|Ç*BñÆÎO'ÊJO¤§§xe›PŠÍ©’~Š›PŠÍž!Ø©’~Š§§xe©’~Š­Òw¡­Òw¡©’~Š°–}O­Òw¡°–}O·liû³ãfÜ­Òw¡·liû";
		-- Hemathion
		[ 18692 ] = "Q|±–Gf¤¼FRªáQ|±–FRªáJÀ¸kQ|±–JÀ¸kPv¹ÀPv¹ÀJÀ¸kNŠ»<M]¡£Gf¤¼Q|±–JÇŸùGf¤¼M]¡£KdxÕIº\127bNæ~\\Næ~\\Iº\127bO\13€åIº\127bJÀƒ\5O\13€åO\13€åJÀƒ\5Pi‰\127O\13€åPi‰\127T÷‡´T÷‡´Pi‰\127U%‹¹Pi‰\127PU‹¬U%‹¹U%‹¹PU‹¬R\25’MPU‹¬N¿¾R\25’MKdxÕNæ~\\O±{\15KdxÕO±{\15R‚u”K~u\24KdxÕR‚u”L]m5K~u\24R‚u”Iõp K~u\24L]m5";
		-- Speaker Mar'grom
		[ 18693 ] = "dê“\24o4‰­e¼‚ëe¼‚ëo4‰­oÅ|\21i=zŒe¼‚ëoÅ|\21màxïi=zŒoÅ|\21o4‰­dê“\24lÓ‘nlÓ‘ndê“\24fÕ•z’\25P\19ŒI]/•ðQ4ŒI]/Žæ`v•ðQ4’ML¹’\25P\19•ðQ4•‡K\15’ML¹•ðQ4\\Bë’ML¹•‡K\15Ë?¸\\Bë•‡K\15¨¦/(¢¢/—¢\0314\31¨¦/(¢\0314\31¦é?±¦é?±¯\19@.¨¦/(«dF¯\19@.¦é?±­—F\
¯\19@.«dF¥€,Ó¢¢/—¨¦/(l\14Îij^ÒÐmBÖÎmBÖÎj^ÒÐjºÕöl\14ÎimBÖÎxlËÌqhÁ°l\14ÎixlËÌy…ÈÁqhÁ°xlËÌxïÄSqhÁ°y…ÈÁvé¿ËqhÁ°xïÄSt`¿4qhÁ°vé¿Ë";
	};
	[ 477 ] = { -- Nagrand
		-- Goretooth
		[ 17144 ] = "ÁˆÀÄ¿ØÂ¼ÁÃÊàÁˆÀÄÁÃÊàÆÎÍVÁÃÊàÃ\31Ò\31ÆÎÍVÃ\31Ò\31ÅÈÓ\18ÆÎÍVÅA[ŠCA‰kDÐÅA[‰kDÐ‹ÆIy‹ÆIy–È?±ÅA[–È?±”÷<\8ÅA[”÷<\8A<\8ÅA[›/AØ–È?±‹ÆIy›/AØ‹ÆIyòQ:òQ:‹ÆIyŒÓO¾›/AØòQ:Ÿ;E‡Ÿ;E‡òQ: ØR×™7V¡ ØR×òQ: ØR×™7V¡ŸbTñ™7V¡Ÿ\13X$ŸbTñ™7V¡\27[JŸ\13X$O.{dMB‚ˆ\\V„÷MB‚ˆW»‹\2\\V„÷W»‹\2MB‚ˆN\\ˆ7N\\ˆ7N\20ŒÓW»‹\2O.{d\\V„÷^(|\27^(|\27\\V„÷_Ëƒ9^(|\27VétêO.{dVétêOHuYO.{dN\1wRO.{dOHuYVétê^(|\27`·xè`·xè]\"r\25VétêY³pbVétê]\"r\25`vrñ]\"r\25`·xè_\20pÑ]\"r\25`vrñe¡ruhŒqNhïirhïirhŒqNj³lPhïirj³lPkûh_h eµhïirkûh_h eµkûh_m²cm²ckûh_n;h*n;h*s\25h$m²cpÿjÍs\25h$n;h*r×j™s\25h$pÿjÍr×j™pÿjÍt`oØt`oØpÿjÍr-sÉr-sÉt\31wöt`oØr-sÉnvwüt\31wönvwürñz~t\31wönvwükÚzxrñz~rñz~kÚzxt9€\19tÐ}Irñz~t9€\19i^uÉkÚzxnvwüi^uÉi³{\15kÚzxi^uÉgfwöi³{\15e¡rugfwöi^uÉhŒqNe¡rui^uÉlçaåh eµm²cg$bÊh eµlçaåi=^«g$bÊlçaå";
		-- Voidhunter Yar
		[ 18683 ] = "R\12²,Q[¸áU¡´\24U¡´\24Q[¸áU¼º\8Q[¸áR\5¾OU¼º\8U¼º\8R\5¾OWÕ¾;R\5¾OSTÂ\25WÕ¾;WÕ¾;STÂ\25U”Å\30[‹À£WÕ¾;U”Å\30U”Å\30Y­Ç\127[‹À£[‹À£Y­Ç\127]ÅÇï[‹À£]ÅÇï_À'_À']ÅÇï`HÇ__À'`HÇ_c3Ä¡_À'c3Ä¡eÏÀbb–»˜_À'eÏÀbb–»˜eÏÀbgX»‘c¯µ¡b–»˜gX»‘c¯µ¡gX»‘gé¶ygÕ²¯c¯µ¡gé¶yaÿ®ùc¯µ¡gÕ²¯fã®¸aÿ®ùgÕ²¯e\4«\21aÿ®ùfã®¸e\4«\21c\31¨´aÿ®ùc\31¨´^V«]aÿ®ù_\20¦\30^V«]c\31¨´Zº¥z^V«]_\20¦\30Zº¥zZ³«Ú^V«]X\3§\23Z³«ÚZº¥zX\3§\23U‡ª\21Z³«ÚU‡ª\21W§¯\0Z³«ÚU‡ª\21Sg­—W§¯\0Sg­—R\12²,W§¯\0R\12²,U¡´\24W§¯\0";
		-- Bro'Gaz the Clanless
		[ 18684 ] = "C\31x\127?ó„\18F\17z\28?ó„\18CM…2F\17z\28?ó„\18@ŽŠCM…2CM…2@ŽŠC©úC\31x\127F\17z\28FR_vJ^^(FR_vF\17z\28I­U\24FR_vJ^^(I­U\24J^^(M\21Y\16I­U\24M\21Y\16NæPØNæPØM\21Y\16ST¢RNM}NæPØST¢VsOŠRNM}ST¢S×FÖRNM}VsOŠS×FÖVsOŠW\23F8R\0259eS×FÖW\23F8U\0048§R\0259eW\23F8qTˆèo\7Œ6s¶Šxo\7Œ6s¶Žžs¶Šxo\7Œ6o!|s¶Žžs¶Žžo!|tÖ’:o!|t¼˜ÁtÖ’:tÖ’:t¼˜Á{’šJt¼˜Á{‹ŸË{’šJNš\15{’šJ{‹ŸË\127·¡\19Nš\15{‹ŸËƒ3žØNš\15\127·¡\19Nš\15ƒ3žØ‡\29šW…Ï•öNš\15‡\29šW…Ï•ö‡\29šW‰\2•¡†8Ž\26…Ï•ö‰\2•¡†8Ž\26‰\2•¡‰Ç‹’…2ˆy†8Ž\26‰Ç‹’ˆ™†¡…2ˆy‰Ç‹’…ðƒä…2ˆyˆ™†¡\127v‡\
…2ˆy…ðƒä\127‚ø\127v‡\
…ðƒä—sµ\30•SºÆ™W»6™W»6•SºÆ™k¼¥™’Åf™k¼¥•SºÆ™k¼¥™’ÅfœôÄfœôÄf™’Åf™QÉDœwË\8œôÄf™QÉD™QÉD•ŽÏ¾œwË\8•ŽÏ¾˜eÒ•œwË\8—sµ\30™W»6škºÍ—sµ\30škºÍšÔµ+¤LÁušÔµ+škºÍ¤LÁuškºÍ£%Åã¤LÁu£%Åã¦fÂ©£%Åã¦+Ç ¦fÂ©¦fÂ©¦+Ç ©ÚÆ\30©\22Á£¦fÂ©©ÚÆ\30©\22Á£©ÚÆ\30µ®´Ž³ã±\12©\22Á£µ®´Ž";
	};
	[ 478 ] = { -- Terokkar Forest
		-- Okrek
		[ 18685 ] = "Q‰ieL/oùS&líL/oùM¸s\31S&lí}Š)è{Í,‹4/Ø{Í,‹\127o2©4/Ø“Ö8\23’G<¿œV>Ì’G<¿š’C©œV>Ì‘·¤”Ž5³¼‘ò²×‘ò²×Ž5³¼“M¸0Ž5³¼uºC“M¸0‘·¤”‘ò²×•\17¦\23";
		-- Doomsayer Jurim
		[ 18686 ] = "[çT9Zra‰]\1aAZra‰\\qhŒ]\1aA]\1aA\\qhŒ_\0h´_\0h´\\qhŒ^\\nß\\qhŒ[çnž^\\nß[çT9]\1aA^BTÉ]VN‘[çT9^BTÉ_—Næ]VN‘^BTÉ^.G\17]VN‘_—Næ\\)Gü]VN‘^.G\17b¶;¹b©>íeµ?Ub¶;¹eµ?UfÈ<~fÈ<~eµ?Ui @‰eµ?UhÎCgi @‰i @‰hÎCgnVB@hÎCgm¿EmnVB@nVB@m¿EmyDE2y\9AnVB@yDE2y\9AyDE2}ÙB@}c>Òy\9A}ÙB@}c>Ò}ÙB@ƒS@ª‚Ð=¸}c>ÒƒS@ª‚Ð=¸ƒS@ªˆ7;¬‡191‚Ð=¸ˆ7;¬‡191ˆ7;¬‹\0025÷Š03:‡191‹\0025÷Š03:‹\0025÷’°2‚’g/¤Š03:’°2‚Œ/PA‹ÀSt“USŒ/PA“US”¨R\25”¨R\25“US—XVf“US–+YQ—XVf—XVf–+YQž\26Z^–+YQœ«]\14ž\26Z^ž\26Z^œ«]\14¡ë_iœ«]\14 ½b\18¡ë_i¡ë_i ½b\18¤Yc{¡ë_i¤Yc{¥Ö`·¥Ö`·¤Yc{ª¬o.¤Yc{¨Áq[ª¬o.ª¬o.¨Áq[¶\23~\20¨Áq[´Ö€ë¶\23~\20";
		-- Crippler
		[ 18689 ] = "GEžcFL£ZNB¡¶NB¡¶FL£ZNp¦NB¡¶Np¦Pù¡×Pù¡×Np¦S\12¦YUtŸ4Pù¡×S\12¦YUtŸ4QëŸÄPù¡×M\21”\31QëŸÄUtŸ4M\21”\31Iè•‡QëŸÄMchIè•‡M\21”\31MchJDŒÓIè•‡JDŒÓMchO\\|Oƒ‰õJDŒÓO\\|Oƒ‰õO\\|VÏ|VÏ|O\\|Vã”\17XÎŽßVÏ|Vã”\17[Ÿ’ñXÎŽßVã”\17XÎŽß[Ÿ’ñ[î/[î/P–ƒ3XÎŽß[î/R\127ùP–ƒ3`\13Ÿ\13]¿¦ÜjÍŸ!jÍŸ!]¿¦Üm\20¦´m\20¦´]¿¦Ü`\6¯b`\6¯bk\"®ìm\20¦´k\"®ì`\6¯beÂ²\25etœp`\13Ÿ\13jÍŸ!f?xlcMyõi*†®cMyõfEˆ´i*†®i*†®fEˆ´mwŽ\26fEˆ´l\21’@mwŽ\26mwŽ\26l\21’@ooŽ(ooŽ(l\21’@pÄ’ëv‡ˆ´ooŽ(pÄ’ëtz…”ooŽ(v‡ˆ´tz…”v‡ˆ´w8„\11w8„\11v‡ˆ´|CˆÔv‡ˆ´z\2Œ\1|CˆÔ|CˆÔz\2Œ\1}ž’,}ž’,z\2Œ\1zx‘ÿzx‘ÿxQ•f}ž’,xQ•fz’˜´}ž’,z’˜´xQ•fu”œCxQ•fs\5˜†u”œCs\5˜†qÊœàu”œCqÊœàs× \19u”œCu”œCs× \19{Úž«s× \19{Ÿ£g{Úž«{Úž«{Ÿ£g„¨ åƒäœw{Úž«„¨ åv_±þq½»\14wy¶fwy¶fq½»\14t¯¼]q½»\14s@ÂMt¯¼]t¯¼]s@ÂMu¡À\12u¡À\12s@ÂMv\17Å2x§Áuu¡À\12v\17Å2x§Áuv\17Å2z=Ä”{¬¿Ëx§Áuz=Ä”\127À{¬¿Ëz=Ä”\127Àz=Ä”ykÊ‹xyÇ\16ykÊ‹z=Ä”xyÇ\16sñÈ™ykÊ‹sñÈ™t\4ÍBykÊ‹~.ºJ{¬¿Ë\127À\127vµÏ~.ºJ\127À\127vµÏ\127À…f«í…f«íƒ\18©î\127vµÏ\127vµÏ{Óµ»~.ºJ|í±T{Óµ»\127vµÏ|í±Tv_±þ{Óµ»v_±þwy¶f{Óµ»";
	};
	[ 479 ] = { -- Netherstorm
		-- Chief Engineer Lorthander
		[ 18697 ] = "C¶`ª@Ul\1G>g†@Ul\1DÐnpG>g†DÐnp@Ul\1@ÑoƒDÐnp@ÑoƒBÊphC¶`ªG>g†J\22`‰G>g†J\22f?J\22`‰J\22`‰J\22f?KPctF\23^pC¶`ªJ\22`‰tFËÌt9Ñ&}«Ì‘\127±ÏH}«Ì‘t9Ñ&\127ËÕ_\127±ÏHt9Ñ&\127ËÕ_t9Ñ&w´ÚŸ|6Û¿\127ËÕ_w´ÚŸv‡ÈÎtFËÌ}«Ì‘”\11\\’ˆ G.ŸH.ŸH’ˆ GŸ\\¤ÝŸ\\¤Ý’ˆ G•Y¬ú•Y¬úí«qŸ\\¤Ýí«q•Y¬ú—š®ù";
		-- Ever-Core the Punisher
		[ 18698 ] = ">„c:¦e\24?ph :¦e\24<\8k]?ph ?ph <\8k]B ld<\8k]@Nr•B ldB ld@Nr•FRm\14@Nr•D¯u\17FRm\14FRm\14D¯u\17J³u\17FRm\14J³u\17O.pØI¦j\2FRm\14O.pØI¦j\2O.pØS3jÀK\28dÉI¦j\2S3jÀ2T§»0|·*7\
®\0130|·*6¡·è7\
®\0130|·*2GÀo6¡·è6¡·è2GÀo9\16¼ó9\16¼ó2GÀo78Æ\16>V½Ò9\16¼ó78Æ\01678Æ\16=«ÈÇ>V½ÒAë»<>V½Ò=«ÈÇ=«ÈÇIïºûAë»<B–µsAë»<IïºûGâ´gB–µsIïºûJŒ·Gâ´gIïºûAå¯iB–µsGâ´gAå¯iGâ´gJ)­ßD¶¦>Aå¯iJ)­ßD¶¦>J)­ßK\8¦éIy£nD¶¦>K\8¦é>p«PAå¯iD¶¦>@!£S>p«PD¶¦>;6¨\16>p«P@!£S:=£¢;6¨\16@!£S4þ¦ö2T§»7\
®\13\6d2boi—lgs—lgsboi—âlÙ—âlÙboiš\8påboi“3{\21š\8påš\8på“3{\21ž.s{“3{\21ž!~Ùž.s{¥%rëž.s{ž!~Ù¨*|à¥%rëž!~Ù¥%rë¨*|à¯ u÷©¦m¿¥%rë¯ u÷©¦m¿¯ u÷°4ieªJe\4©¦m¿°4ie¬ÌV\17ªJe\4°4ie§»YîªJe\4¬ÌV\17ª¹QÊ§»Yî¬ÌV\17¡‰VÕ§»Yîª¹QÊ¢nPß¡‰VÕª¹QÊ¦šO\7¢nPßª¹QÊžUP\26¡‰VÕ¢nPßžUP\26œ/Y“¡‰VÕ—eU›œ/Y“žUP\26˜ÛO¤—eU›žUP\26šáM}˜ÛO¤žUP\26—eU›”m\\qœ/Y“”m\\q˜e`'œ/Y“”m\\q\6d2˜e`'\6d2—lgs˜e`'";
		-- Nuramoc
		[ 20932 ] = "Uã@oRøGü[6GöRøGüT%NÙ[6Gö[6GöT%NÙ\\<Nß\\<NßT%NÙ\\‘U¯\\‘U¯T%NÙU`Wé\\‘U¯U`WéWYá\\<Nß\\‘U¯]íR–Uã@o[6Gö\\6D¶W”<]Uã@o\\6D¶\\6D¶a A\6W”<]W”<]a A\6X\00352_—6ŽX\00352a A\6\\¿0¾X\00352_—6ŽZk0¤X\00352\\¿0¾\\6D¶_BCÃa A\6‡“Œ\14…zŽ\26Š\22ŽË…zŽ\26†8šçŠ\22ŽË†8šçˆ\29œÓŠ\22ŽËŠ\22ŽËˆ\29œÓ˜º’{˜º’{ˆ\29œÓ£ê¡:§y’{˜º’{£ê¡:­\7•ý§y’{£ê¡:­\7•ý£ê¡:°‚Ÿ°‚Ÿ£ê¡:¨\9¥µ°·¢{°‚Ÿ¨\9¥µ°·¢{¨\9¥µªd§\3<‹Æš:ÔÈr;^Ì\27C\5Ê˜<‹Æš;^Ì\27;^Ì\27@4Ñ{C\5Ê˜C\5Ê˜@4Ñ{I\16ÒtC\5Ê˜I\16ÒtJxÊÚJxÊÚI\16ÒtN¸ÎËJxÊÚN¸ÎËOÆ®OÆ®N¸ÎËZÔÍvOÆ®ZÔÍveÁÃZÔÍvd•Ì\27eÁÃeÁÃd•Ì\27nHÇylúÀòeÁÃnHÇynHÇyt÷Ç>lúÀòo.½ìlúÀòt÷Ç>o.½ìt÷Ç>vÈº…mI´¼o.½ìvÈº…vÈº…rˆ±:mI´¼rˆ±:pv±–mI´¼t÷Ç>nHÇys•É=";
	};
	[ 486 ] = { -- Borean Tundra
		-- Old Crystalbark
		[ 32357 ] = "5SC¯4\31Lq8âJ™8âJ™4\31Lq;#S34\31Lq7¡XÁ;#S3;#S37¡XÁAoUð7¡XÁ>\14^\14AoUðAoUð>\14^\14IrW€AoUðIrW€I™Q'I™Q'IrW€RTUSN(K^I™Q'RTUSRTUSU%OåN(K^U%OåQ-K\28N(K^U%OåRTUST`TW†M]U%OåT`TT`T[‹L\21W†M]XïEýW†M][‹L\21XïEý[‹L\21\\\"Cˆ\\\"CˆV¡C{XïEýZ#?¸V¡C{\\\"CˆU\30?;V¡C{Z#?¸V\23;0U\30?;Z#?¸5SC¯8âJ™9áC¢";
		-- Fumblub Gearwind
		[ 32358 ] = "–L;^–\
D¨›wD¶–\
D¨˜lGl›wD¶–L;^›wD¶Ÿ|<ŸŸ|<Ÿ›wD¶¢@A\26¢@A\26›wD¶OEz¢@A\26OEz¤?H\23OEzžpJk¤?H\23¤?H\23žpJk¢×SGžpJk\\Rn¢×SG\\Rn„Xš¢×SG„Xšžó[‹¢×SG¢×SGžó[‹ª‹WRª‹WRžó[‹®![d®![džó[‹®«cþ®![d®«cþ¸¦aÿ±äXÈ®![d¸¦aÿ¼\14ZD±äXÈ¸¦aÿ³9S{±äXÈ¼\14ZD³9S{¼\14ZD½ÌR:µÏO!³9S{½ÌR:¸>M²µÏO!½ÌR:½ÌR:½cG€¸>M²½cG€¹…GÏ¸>M²»ÆE`¹…GÏ½cG€¯vOƒ³9S{µÏO!³\31LŸ¯vOƒµÏO!®\26JÇ¯vOƒ³\31LŸ±ÞIk®\26JÇ³\31LŸ°òC\5®\26JÇ±ÞIk®\26JÇ°òC\5¬\27:e¬\27:e°òC\5²{@N²{@N¸\127;\28¬\27:e¸\127;\28±-2ÿ¬\27:eª\0215F¬\27:e±-2ÿ¨ *=ª\0215F±-2ÿ¨ *=¤F0Øª\0215F£t'L¤F0Ø¨ *=£t'L˜e0±¤F0Ø˜e0± A71¤F0Ø A71˜e0±–L;^ A71–L;^Ÿ|<Ÿ™­#ˆ˜e0±£t'L›Ó\"°™­#ˆ£t'L¸\127;\28²{@N¶Á@·¸\127;\28¶Á@·¸ü>¤";
		-- Icehorn
		[ 32361 ] = "Ìút¼ÌÙy\29ÚÚu\11ÚÚu\11ÌÙy\29Û\14y Ð\12M\1Î}PòÜIV”Î}PòÜ\"[’ÜIV”í.TÉÜIV”Ü\"[’ì!PNÜIV”í.TÉâMb¶à-f+äzeéà-f+âgiQäzeé";
	};
	[ 488 ] = { -- Dragonblight
		-- Tukemuth
		[ 32400 ] = "‡“˜X‘\25‰7“,yx“,yx‘\25‰7“•ƒS“•ƒS‘\25‰7”ýŽp”,™Í”ýŽp‘\25‰7”ýŽp”,™Í–¡‘[–¡‘[”,™Í™³’½™³’½”,™Íœ¿ž±œ¿ž±”,™Í˜§Ÿå™³’½œ¿ž± o–´œ‹‘‰™³’½ o–´ž\\—œ‹‘‰ o–´ž\\— o–´£SŠ0Ÿ.ˆyž\\—£SŠ0£SŠ0œàsÃŸ.ˆy£SŠ0 \26oœàsÃ™ŒoŠœàsÃ \26oœ‹l¿™ŒoŠ \26o¤‡`\26œ‹l¿ \26o¤‡`\26¢&\\\27œ‹l¿¢&\\\27¤‡`\26¦»`U©QY ¢&\\\27¦»`U©QY ¦»`U«ú`ì«ú`ì¦»`U¨Ôb×¨Ôb×ª~k~«ú`ì«ú`ìª~k~¯rGª~k~¬žu\17¯rG¯rG¬žu\17µ~\\¬žu\17²t€Þµ~\\µ~\\²t€ÞµÖˆ^²t€Þ²Z†€µÖˆ^µÖˆ^²Z†€ª\2š\28ª\2š\28­\27OµÖˆ^©QY «ú`ì®ù\\C­žW§©QY ®ù\\C­žW§®ù\\Cµ®X\3³@S,­žW§µ®X\3³@S,µ®X\3·rTZ³ŽO'³@S,·rTZ·\23LŸ³ŽO'·rTZ³ÝHK³ŽO'·\23LŸ¯ÿKx³ŽO'³ÝHK°\19E¼¯ÿKx³ÝHK¬\21Hš¯ÿKx°\19E¼¬\21Hš­—N±¯ÿKx¬\21Hš©\127Nv­—N±­—N±©\127Nv­žW§­žW§©\127Nv©QY š0jx™ŒoŠœ‹l¿–ýj\9™ŒoŠš0jx™ŒoŠ–ýj\9“\24n¸“©h7“\24n¸–ýj\9‘Sn“©h7–ýj\9šPRþ“©h7‘Sn‘Snš6OØšPRþpN¤š6OØ‘SnpN¤—€KÓš6OØpN¤™kGü—€KÓ™ŒoŠ“\24n¸—8q&—8q&“\24n¸—Ev‡—Ev‡“\24n¸“,yx“,yx–”{\28—Ev‡“,yx“•ƒS–”{\28‡“˜XŠWš¦‘\25‰7";
		-- Crazed Indu'le Survivor
		[ 32409 ] = "3\18ŠÚ%÷”Â4S4%÷”Â'R™^4S43\18ŠÚ4S4<íŒc3\18ŠÚ<íŒc=\8†\4=\8†\4<íŒc?'‡»?'‡»<íŒcHÈšáHÈšá<íŒcH\23¡@HÈšáH\23¡@Kk \26J…š\28HÈšáKk \26J…š\28Kk \26OU—ÛMw“ÉJ…š\28OU—ÛMw“ÉOU—ÛW$’\12Uý\20Mw“ÉW$’\12(Õoª%Ép¾%ŽwR+)yk(Õoª%ŽwR%ŽwR) {/+)yk";
		-- Scarlet Highlord Daion
		[ 32417 ] = "µ®2‚³•7Ü¸á9Á³•7Ü¶§C@¸á9Á¸á9Á¶§C@¾\26AN¶§C@¼/G”¾\26ANÄ¯F”¾\26AN¼/G”Ä¯F”¼/G”ÃSHâÛ¹YáÚW\\~â¢[çÚW\\~Ü}m˜â¢[çÜ}m˜ß‰n!â¢[çá£YÎÛ¹Yáâ¢[ç±n½V¯|Å®²øÀA¯|Å®±@Æs²øÀA±n½V²øÀAµ\
½O´Ï¸Q±n½Vµ\
½Oµ\
½O¹r»w´Ï¸Q¶ü·R´Ï¸Q¹r»w¸è­ß¶ü·R¹r»w¶´­¿¶ü·R¸è­ß¹r»wµ\
½O·\127¾¹r»w·\127¾»ÌÀG·\127¾º’Áø»ÌÀG";
	};
	[ 490 ] = { -- Grizzly Hills
		-- Grocklar
		[ 32422 ] = "\26*f8\25ÁjW\30«f_\30«f_\25ÁjW!ër\5\25ÁjW\29Óu\4!ër\5!ër\5\29Óu\4'\30yÛ\29Óu\4\30ž\127ò'\30yÛ'\30yÛ\30ž\127ò(1€o\30ž\127ò'R\13(1€o\30ž\127ò\28Æ‘a'R\13\28Æ‘a%S’,'R\13%S’,\28Æ‘a\29¹“¼\27Ídz\26*f8\30«f_\"Ê²×\27’³M\27Q·\23%9¶l\"Ê²×\27Q·\23\"Ê²×%9¶l(X¯A(X¯A%9¶l)­¶\16(X¯A)­¶\16+¬°½+¬°½)­¶\0162G¶†)­¶\16.\27»Ú2G¶†2G¶†.\27»Ú:\9¿b9“¶E2G¶†:\9¿b;…½\\9“¶E:\9¿bDM–Ü5SB3¢ÄDM–Ü3¢ÄBT™x3Ã–ÜBT™x3¢ÄBT™x3Ã–Ü5êšÚDM–Ü<Ú‰À5SBD%‹)<Ú‰ÀDM–ÜB ˆ§<Ú‰ÀD%‹)HRh*F\23k‹J…k=F\23k‹HKn¾J…k=";
		-- Seething Hate
		[ 32429 ] = "D\11q[C,vfH†r•H†r•C,vfI#vâC,vfDÐz’I#vâW$zWU`\127[=\127|U`\127Y\9‚ˆ[=\127|W$zW[=\127|[]{/d9yºaN|úh\3z’h\3z’aN|úi \127¤aN|úa£€Øi \127¤a£€Øfð„\18i \127¤";
		-- Syreian the Bonecarver
		[ 32438 ] = "žvW§›çXÈ Ë[³›çXÈ„`\13 Ë[³„`\13Ÿªb: Ë[³ Ë[³Ÿªb:¦\30^B£êY™ Ë[³¦\30^B£êY™¦\30^B©™Vð©™Vð¦\30^B¬¥\\q¬¥\\q¦\30^B­waÿ¦\30^B§dÃ­waÿ§dÃ­\14kÚ­waÿ­\14kÚ§dÃ§kî­\14kÚ§kî«\1nO¥öTÝ£êY™©™Vð©\9M¿¥öTÝ©™Vð¦\30K\15¥öTÝ©\9M¿¦\30K\15©\9M¿¬/K\2­ÅB\25¦\30K\15¬/K\2°£Hâ­ÅB\25¬/K\2°£Hâ¬/K\2­æLC°£Hâ­æLC´\17M¿´\17M¿­æLC°\6S©´\17M¿°\6S©ºCR\5ºCR\5°\6S©¾.Y¦¹îbþ¾.Y¦°\6S©¾.Y¦¹îbþ¾ìao¾ìao¹îbþ»ÆjxÄ\4cˆ¾ìao»ÆjxÄ\4cˆ»ÆjxÅ2lÓ¾ƒqNÅ2lÓ»Æjx¾ƒqN»Æjx¼¸pHÂ©`Ä¾ìaoÄ\4cˆ­ÅB\25°£Hâ± D¯­ÅB\25± D¯²T?ù²T?ù¯ª=w­ÅB\25±n=æ¯ª=w²T?ù";
		-- Arcturis
		[ 38453 ] = "QåBNBBQÊ’@NBBNi’MQÊ’@";
	};
	[ 491 ] = { -- Howling Fjord
		-- Perobas the Bloodthirster
		[ 32377 ] = "€·\12\8\127ª\15ß‚ˆ\17å‚u\9\29€·\12\8‚ˆ\17å‚u\9\29‚ˆ\17åˆD\26\127ˆD\26\127‚ˆ\17åˆK!ÿ‹Ÿ\29/ˆD\26\127ˆK!ÿ‹Ÿ\29/ˆK!ÿŠ)\"T˜Û.Ò—š3G¤2[—š3G›w9Œ¤2[—š3G™ :D›w9Œ±{+W¬I'\
ªC.¿±{+WªC.¿¬p0ª®Ë%F¬I'\
±{+W³\11&Ž®Ë%F±{+W³\11&Ž±{+W·Á*è³\11&Ž·Á*è¹À#\31¶§\30Ì³\11&Ž¹À#\31¸>\28˜¶§\30Ì¹À#\31";
		-- Vigdis the War Maiden
		[ 32386 ] = "­Ì“g­¤–»±:“t±:“t­¤–»³g™=±:“t³g™=´\17H´\17H³g™=¶®›<´\17H¶®›<ÀëßÀëß¶®›<Á\25žÁ\25ž¶®›<¹³ŸùÁ\25ž¹³Ÿù½‘¡uÁˆõ´\17HÀëßÁˆõ´t„ð´\17H´t„ðÁˆõÃ\5€\6Ã\5€\6¯·~¾´t„ðÃ\5€\6µ€n—¯·~¾µ€n—®!u¨¯·~¾µ€n—¯ØpÄ®!u¨µ€n—Ã\5€\6ÃãsÂ{hÕµ€n—Ããs½vemµ€n—Â{hÕÀ\19e?½vemÂ{hÕ¹xe\24µ€n—½vem»¬b{¹xe\24½vem";
		-- King Ping
		[ 32398 ] = "O!(M/ŽžST“¯M/ŽžPA—\16ST“¯>I¢Ð>\14¥SCa¦f>I¢ÐCa¦fFfŸ\26FfŸ\26Ca¦fFµ¤ãN¿¯ìMÌ½5Pì°\19MÌ½5P\13½¸Pì°\19QN½\0Q\19ÃþS,½\20Q\19ÃþRëÄ\30S,½\20SaÉ¬QåÏWšÌjQåÏSˆÑWšÌjW†É\15SaÉ¬WšÌj";
	};
	[ 492 ] = { -- Icecrown
		-- Putridus the Ancient
		[ 32487 ] = "v®‰Œr×ˆDrh•›v®‰Œrh•›v?•\30v?•\30rh•›{P¬žrh•›wé®{P¬žr×ˆDv®‰Œz\15\127\20wE{˜r×ˆDz\15\127\20wE{˜z\15\127\20ƒäkô‚\12f®wE{˜ƒäkô‚\12f®ƒäkôŠxgÎŠkaÄ‚\12f®ŠxgÎŠkaÄŠxgÎ–ýh´ŠkaÄ–ýh´˜ºct˜ºct–ýh´§>s¼–ýh´¤`y*§>s¼§>s¼¤`y*®—“\18¤`y*«\"•€®—“\18®—“\18«\"•€²@¦f«\"•€®±§e²@¦f²@¦f®±§e³Ö©*®±§e­«©x³Ö©*­«©x­ì¯ì³Ö©*³Ö©*­ì¯ì´,°´,°­ì¯ì°ë³\31";
		-- Hildana Deathstealer
		[ 32495 ] = "HXu¨DÝ{ŸIÎwöDÝ{ŸEê}OIÎwöHXu¨IÎwöL²u\11J\127qÞHXu¨L²u\11NÒmVJ\127qÞL²u\11R&nìNÒmVL²u\11NÒmVR&nìS9ieO¾hšNÒmVS9ieR\25dtO¾hšS9ieLŸb×O¾hšR\25dtO\7` LŸb×R\25dtK)]„LŸb×O\7` N.]\1K)]„O\7` LçT\31K)]„N.]\1LçT\31N.]\1P.S¶M}N‘LçT\31P.S¶IÛL¥LçT\31M}N‘LIJÇIÛL¥M}N‘JJF¡IÛL¥LIJÇMóEÂJJF¡LIJÇM\14AªJJF¡MóEÂQÄB M\14AªMóEÂQÄB MóEÂP±EêQÄB P±EêU¨FÜP±EêUtIÁU¨FÜ^(DŽU¨FÜUtIÁ]\1B3U¨FÜ^(DŽ]\1B3^(DŽ`\19@\0]Ó?\13]\1B3`\19@\0]Ó?\13`\19@\0`ò<ç]p<j]Ó?\13`ò<ç_\26:Ô]p<j`ò<çK)]„HRdðLŸb×HRdðJºfRLŸb×HRdðJ\127qÞJºfRHRdðHXu¨J\127qÞ†\17Š~†\
ŽB‡§²†\17Š~‡§²‰*Šôˆr‡Á†\17Š~‰*Šôˆr‡Á‰*Šô‹¬ˆ1‹\2„\18ˆr‡Á‹¬ˆ1ŽÒ„2‹\2„\18‹¬ˆ1ŽÒ„2‹¬ˆ1ŽUˆrŽÒ„2ŽUˆr’äŠû–öÞ’äŠûŽUˆr—˜K–öÞŽUˆr–öÞ—˜Kš6—R—˜K™’úš6—R—˜K–öp™’ú–öp—E ò™’ú–öp“Ðžv—E ò“Ðžv“M¡£—E ò’äŠû–öÞ™\28‰Í—ü‡§’äŠû™\28‰Í";
		-- High Thane Jorfus
		[ 32501 ] = "­\14^\\ª¦_å¯Nf\30ª¦_å­ßjÇ¯Nf\30¯Nf\30­ßjÇ°½f_­ßjÇ°Ak˜°½f_°½f_°Ak˜´\17iõ³\24eã°½f_´\17iõ³\24eã´\17iõ¸ e%µÖbþ³\24eã¸ e%µÖbþ¸ e%¸º_.µÜ\\/µÖbþ¸º_.µÜ\\/¸º_.½\7Z^»\21W¡µÜ\\/½\7Z^»\21W¡½\7Z^¿ËPo½;Oi»\21W¡¿ËPovðÛq\127òË\14xXÇÁzûÅ_xXÇÁ\127òË\14\127òË\14vðÛq\127ÒàA\127ÒàAvðÛq|PáaN\7›…M\1 uPòœÌM\1 uPN¡©PòœÌM\1 uPA¯PN¡©PN¡©PA¯S©°:PA¯Oƒ³ZS©°:S©°:Oƒ³ZP–µãS©°:P–µã\\d¶+\\d¶+\\d°½S©°:\\d°½\\d¶+]„³›";
	};
	[ 493 ] = { -- Sholazar Basin
		-- Aotona
		[ 32481 ] = "j’\7c÷kÍ’þc÷d\11–>kÍ’þd\11–>i\127œúkÍ’þj’\7kÍ’þp\6·j’\7p\6·r{ˆlr{ˆlp\6·y#“\24r{ˆly#“\24{À‰îiÇƒFj’\7r{ˆlp\26\25iÇƒFr{ˆll\8€4iÇƒFp\26\25‡§‚©†¡†¡ˆD‰­‡§‚©ˆD‰­øˆ“[°‡§‚©øˆ“’°…¡[°øˆ“Š\28\127\0‡§‚©[°:¢äŽË©*•ã®ù:¢ä•ã®ù–+Ÿª„2²ˆ‚&¼\1Šî·\29‚&¼\1‰#¾BŠî·\29‚&¼\1„ãÁ¶‰#¾Bfö­ŠeŽ±TgK´Âk\8ªÚfö­ŠgK´Âsñ®«k\8ªÚgK´Âlà¸ºsñ®«gK´ÂgK´Âl²Àòlà¸ºgK´ÂiÛÃÖl²Àòu?´êsñ®«là¸ºu?´êlà¸ºsg¸0sñ®«pÑ«<k\8ªÚ";
		-- King Krush
		[ 32485 ] = "A–z…A\12\127\0F\17{ÓA\12\127\0C@AF\17{ÓF\17{ÓC@AJ0œF\17{ÓJ0œL„|¥L„|¥J0œN;~¾J0œM‹ƒÃN;~¾M‹ƒÃJ0œG\
‹wM‹ƒÃG\
‹wK\2‹àG\
‹wI\3¦+K\2‹àK\2‹àI\3¦+LÆ¦8I\3¦+FÜ¼wLÆ¦8FÜ¼wJ™½žLÆ¦8N;hÛA–z…F\17{ÓLPd\5A–z…N;hÛLPd\5N;hÛTte`QÄa4LPd\5Tte`QÄa4Tte`XeS&V\17N¸QÄa4XeS&V\17N¸XeS&ZçPƒZ¬KPV\17N¸ZçPƒZ¬KPZçPƒ_oL\14ZçPƒ^«Qb_oL\14végâr×lww´påw´pår×lws\31oz’g“végâw´på~(m\27z’g“w´påw´påyõtÐ~(m\27~(m\27yõtÐ\127Oyr\127OyryõtÐ{dyõ‚\25k³~(m\27\127Oyr‰\127m(‚\25k³\127Oyr‰\127m(†€e¡‚\25k³‰Xfs†€e¡‰\127m(„9ËÓnÍB…\30Ñ‚nÍBƒtÖ…\30Ñ‚…\30Ñ‚ƒtÖˆQÔFƒtÖ‡8ÛôˆQÔFˆQÔF‡8Ûô‹çØõˆQÔF‹çØõjÒ@jÒ@‹çØõ‘ØxjÒ@‘Øx–¡Ìó‘Øx”÷ÚŸ–¡Ìó–¡Ìó”÷ÚŸOÎ}OÎ}”÷ÚŸŸßÚ’OÎ}ŸßÚ’¥E×õOÎ}¥E×õ¨QÏË¢{ËqOÎ}¨QÏË¨^Ì5¢{Ëq¨QÏË¥»ÉÔ¢{Ëq¨^Ì5¤Ì„jÒ@–¡Ìó“›Èõ¤Ì„–¡Ìó";
		-- Loque'nahak
		[ 32517 ] = "³Ö¯N±‰³\31¸è¸k¸è¸k±‰³\31±£¸\3³É»¥¸è¸k±£¸\3¸è¸k³É»¥¶Ü»à¸è³\24³Ö¯N¸è¸k¶§¯;³Ö¯N¸è³\24ªk¿\13¥ãÉ#° Æ8¥ãÉ#«’Í¤° Æ8«’Í¤¥ãÉ#¦\23Ì¸­ß¾.ªk¿\13° Æ8‚uÉ…~;Ð\12„LÒñ~;Ð\12~HÓz„LÒñ~HÓz‚×è„LÒñ„LÒñ‚×è…8ÖÎ“Ã3n‘A6S™\0096€‘[;Ÿ™\0096€‘A6S™\9;’™\0096€‘[;Ÿ‘[;Ÿ–â?v™\9;’‘[;Ÿ“M?b–â?v–Ï3n“Ã3n™\0096€[˜FðXÕJJX§MV`\0R\25[˜FðX§MVX§MV]úT¢`\0R\25L¥£ÃIÎ¬wOå¤ãOå¤ãIÎ¬wR\19©ÀKÀ¯AR\19©ÀIÎ¬wR\19©ÀKÀ¯APU¯å3×²32Þ¹û5Éºd3×²35Éºd9†¹03×²39†¹09è°‚7_®\\3×²39è°‚";
	};
	[ 495 ] = { -- The Storm Peaks
		-- Time-lost Proto Drake
		[ 32491 ] = "H­d`DtaœCZf®H­d`CZf®G\23gÎCZf®C¢nHG\23gÎG\23gÎC¢nHG8m„G8m„C¢nHHètC¢nHEŽuÜHètHètEŽuÜIX}\\EŽuÜEã}àIX}\\IX}\\Eã}àIk„‡Ik„‡Eã}àD3ŽBIk„‡D3ŽBGâŽ.GâŽ.D3ŽBGüš³D3ŽBDg›<Güš³Güš³Dg›<Iü¢:Dg›<G\17¦\3Iü¢:Iü¢:G\17¦\3LŸ¥`G\17¦\3J…©ÇLŸ¥`LŸ¥`J…©ÇNóªîJ…©ÇK\8¯‰NóªîJ…©ÇG§­žK\8¯‰G§­žCø»dK\8¯‰K\8¯‰Cø»dG§»ôG§»ôCø»dG´Á×G´Á×Cø»dDMÂ¼G´Á×DMÂ¼I“Æ\3DMÂ¼F8ÈDI“Æ\3I“Æ\3F8ÈDN±ÉxF8ÈDM¿ÎbN±ÉxN±ÉxM¿ÎbUË~M¿ÎbUzÐ4UË~UË~UzÐ4[\28ÎOZDÉŸUË~[\28ÎOZDÉŸ[\28ÎO^\\ÊÍ]\14ÅLZDÉŸ^\\ÊÍ]\14ÅL^\\ÊÍa:Æïa:Æï^\\ÊÍb\5ÌÓ^\\ÊÍ^ìÏËb\5ÌÓb\5ÌÓ^ìÏËcaÏHcaÏH^ìÏËa\25Ô\17eÖÐÿcaÏHa\25Ô\17a\25Ô\17etÖ1eÖÐÿs÷Ð×eÖÐÿetÖ1uFÕYs÷Ð×etÖ1s÷Ð×uFÕYxÇÓFwXÎås÷Ð×xÇÓFwXÎåxÇÓF}\"Ì]{dÇèwXÎå}\"Ì]{dÇè}\"Ì]~‘Èü{dÇè~‘ÈüGµðGµð~5²½{dÇè~5²½Gµð‰±N}\"®!~5²½‰±N€U¬C}\"®!‰±NyÇ¤}\"®!€U¬C|²¢ÊyÇ¤€U¬CvÂŠyÇ¤|²¢ÊzŒœcvÂŠ|²¢ÊzŒœct÷šûvÂŠwy–öt÷šûzŒœcwy–ör\5š\2t÷šûwy–ösZ”µr\5š\2o4•»r\5š\2sZ”µo4•»jõ™ r\5š\2r\5š\2jõ™ m«.jõ™ h žUm«.h žUkç ëm«.fö«Ÿkç ëh žUfö«ŸjW¬Ckç ëfö«Ÿe¯±‚jW¬Ce¯±‚i*³FjW¬Ce¯±‚dg´\30i*³Fdg´\30fm¸Ái*³Fdg´\30a–·7fm¸Áa–·7c\31¼\1fm¸Áa–·7]Ù»ôc\31¼\1]Ù»ôauÀÊc\31¼\1]Ù»ô]\14ÅLauÀÊ]\14ÅLa:ÆïauÀÊ]5³¼]Ù»ôa–·7`¾°ÿ]5³¼a–·7[³®\20]5³¼`¾°ÿ_ª«ô[³®\20`¾°ÿ]í¨™[³®\20_ª«ôY³«’[³®\20]í¨™\\\21¦ÕY³«’]í¨™W+ªPY³«’\\\21¦Õ\\\21¦ÕVÈ¤W+ªPVÈ¤Pb¥fW+ªPPb¥fNóªîW+ªPPb¥fLŸ¥`Nóªî]àŸvVÈ¤\\\21¦Õ]àŸv\\\21¦Õ^ù¤É]àŸv^ù¤Éa:£%a4œÓ]àŸva:£%d9ž¤a4œÓa:£%hÕ—\
a4œÓd9ž¤eŽ”`a4œÓhÕ—\
lP“SeŽ”`hÕ—\
lP“Sfs—eŽ”`m5ŒCfs—lP“SqÄÿm5ŒClP“SqÄÿp|Œjm5ŒCp|ŒjqÄÿv§Šçv§ŠçqÄÿx\3v§Šçx\3~.‰\9|¹ƒñv§Šç~.‰\9|¹ƒñ~.‰\9‚½‚½\1274€N|¹ƒñ‚½‚½\1274€N‚½‚½ƒ¼~¾\127|\21\1274€Nƒ¼~¾ƒ@zû\127|\21ƒ¼~¾ƒ@zû}‘vµ\127|\21ƒ@zû\127\20q\19}‘vµy\22o\26}‘vµ\127\20q\19{djWy\22o\26\127\20q\19w€jJy\22o\26{djWzûfYw€jJ{djWwšdZw€jJzûfYwšdZzûfY|jcay\9`vwšdZ|jcay\9`v|jca‚ÐX\9‚ÐX\9|jca†?ZQ‚ÐX\9†?ZQ‡\23Véƒ÷T¨‚ÐX\9‡\23Véƒ÷T¨‡\23Vé‡ÕR@‚©Qƒ÷T¨‡ÕR@…µN5‚©Q‡ÕR@…µN5\127OO}‚©Q…µN5€ëJá\127OO}€ëJáwsM\21\127OO}€ëJáwyGÏwsM\21wyGÏnOM<wsM\21wyGÏn5GÁnOM<n5GÁb-McnOM<b-Mcc¢R\25nOM<b-Mc[…S•c¢R\25[…S•]\1Xrc¢R\25[…S•S9[q]\1XrS9[qU?_ß]\1XrS9[qRÑaoU?_ßL\1^!RÑaoS9[qL\1^!L\14cœRÑaoL\1^!Fö^¸L\14cœL\14cœFö^¸H­d`Fö^¸DtaœH­d`jº‰ fs—m5ŒCiÔ…Ffs—jº‰ iÔ…Fi­|\"fs—f\30rÞfs—i­|\"iŒpNf\30rÞi­|\"e›pNf\30rÞiŒpNgÁkxe›pNiŒpNcZm¥e›pNgÁkxd÷hycZm¥gÁkxaNl‘cZm¥d÷hya[fÂaNl‘d÷hy]PiKaNl‘a[fÂ]PiK^Ùn\20aNl‘]PiK[’q½^Ùn\20V\
qÄ[’q½]PiK[’q½V\
qÄS,yÎMÙxèS,yÎV\
qÄMÙxèN«~žS,yÎMÙxèIX}\\N«~žN«~žIX}\\Ik„‡";
		-- Dirkee
		[ 32500 ] = "b”¢^‘\19]B”L]B”L^\\™\9b”¢b”¢^\\™\9d9–ï^\\™\9b-œôd9–ïb A^‘\19b”¢aª‹’^‘\19b Aaª‹’b AcÐŒ~aª‹’cÐŒ~ezŠ#fÈ†saª‹’ezŠ#fÈ†sezŠ#i0‰ fÈ†si0‰ j’…ŽgšƒŽfÈ†sj’…Žj’…Ži†€ogšƒŽi†€ohr€‰gšƒŽi\2f\4gÈjºj¦i\22j¦i\22gÈjºlwmÌgÈjºj6p\13lwmÌi\2f\4j¦i\22oicþh“c×i\2f\4oicþmóauh“c×oicþ¯¤{q«\8vE«\1}}¯¤{q«\1}}­Å\127Å­Å\127Å«\1}}¬5\127Å­¤tŽ«\8vE¯¤{q«Útg«\8vE­¤tŽ";
		-- Vyragosa
		[ 32630 ] = "I\29e\4Dãb@CÊgRI\29e\4CÊgRG†hrCÊgRD\18nìG†hrG†hrD\18nìG§n(G§n(D\18nìIXu%D\18nìEýv€IXu%IXu%Eýv€IÇ~\0Eýv€FR~ƒIÇ~\0IÇ~\0FR~ƒIÛ…+IÛ…+FR~ƒD¢ŽæIÛ…+D¢ŽæHRŽÒHRŽÒD¢ŽæHl›WD¢ŽæDÖ›àHl›WHl›WDÖ›àJk¢ÝDÖ›àG€¦§Jk¢ÝJk¢ÝG€¦§M\14¦\3G€¦§JõªkM\14¦\3M\14¦\3JõªkOb«’JõªkKx°-Ob«’JõªkH\23®BKx°-H\23®BDg¼\7Kx°-Kx°-Dg¼\7H\23¼˜H\23¼˜Dg¼\7H$Â{H$Â{Dg¼\7D¼Ã`H$Â{D¼Ã`J\2Æ§D¼Ã`F¨ÈèJ\2Æ§J\2Æ§F¨ÈèO!Ê\28F¨ÈèN.Ï\6O!Ê\28O!Ê\28N.Ï\6UðÌ\"N.Ï\6UêÐ×UðÌ\"UðÌ\"UêÐ×[‹ÎòZ³ÊCUðÌ\"[‹ÎòZ³ÊC[‹Îò^ÌËq]}ÅðZ³ÊC^ÌËq]}Åð^ÌËqaªÇ“aªÇ“^ÌËqbuÍv^ÌËq_\\ÐobuÍvbuÍv_\\ÐocÐÏìcÐÏì_\\Ðoa‰ÔµfEÑ£cÐÏìa‰Ôµa‰ÔµeãÖÕfEÑ£tgÑ{fEÑ£eãÖÕuµÕýtgÑ{eãÖÕtgÑ{uµÕýy7ÓêwÈÏ‰tgÑ{y7ÓêwÈÏ‰y7Óê}‘Í\0{ÓÈŒwÈÏ‰}‘Í\0{ÓÈŒ}‘Í\0\127\0ÉŸ{ÓÈŒ\127\0ÉŸ·¶”·¶”~¤³`{ÓÈŒ~¤³`·¶”ø±ñ}‘®Å~¤³`ø±ñ€Ä¬æ}‘®Åø±ñz6¥%}‘®Å€Ä¬æ}\"£nz6¥%€Ä¬æw1ž.z6¥%}\"£nzû\7w1ž.}\"£nzû\7uf›Ÿw1ž.wé—šuf›Ÿzû\7wé—šruš¦uf›Ÿwé—šsÉ•Yruš¦o¤–_ruš¦sÉ•Yo¤–_kdšCruš¦ruš¦kdšCn\27ÒkdšCi\16žùn\27Òi\16žùlV¡n\27Ògf¬ClV¡i\16žùgf¬CjÇ¬ælV¡gf¬Cf\30²&jÇ¬æf\30²&i™³êjÇ¬æf\30²&dÖ´Âi™³êdÖ´ÂfÜ¹di™³êdÖ´Âb\5·ÛfÜ¹db\5·Ûc¼¥fÜ¹db\5·Û^I¼˜c¼¥^I¼˜aåÁnc¼¥^I¼˜]}ÅðaåÁn]}ÅðaªÇ“aåÁn]¥´`^I¼˜b\5·Ûa-±£]¥´`b\5·Û\\\"®¸]¥´`a-±£`\26¬˜\\\"®¸a-±£^\\©=\\\"®¸`\26¬˜Z#¬5\\\"®¸^\\©=\\„§yZ#¬5^\\©=WšªôZ#¬5\\„§y\\„§yW8¥%WšªôW8¥%PÑ¦\
WšªôPÑ¦\
Ob«’WšªôPÑ¦\
M\14¦\3Ob«’^O \26W8¥%\\„§y^O \26\\„§y_i¥m^O \26_i¥maª£Éa£w^O \26aª£Éd¨ŸHa£waª£ÉiD—­a£wd¨ŸHeý•\4a£wiD—­l¿“÷eý•\4iD—­l¿“÷fãŽ;eý•\4m¥ŒæfãŽ;l¿“÷r3‘£m¥Œæl¿“÷r3‘£pë\14m¥Œæpë\14r3‘£w\23‹‹w\23‹‹r3‘£xr4w\23‹‹xr4~ž‰­}(„•w\23‹‹~ž‰­}(„•~ž‰­ƒ,ƒa\127¤€ò}(„•ƒ,ƒa\127¤€òƒ,ƒa„,\127b€\13|¹\127¤€ò„,\127bƒ¯{Ÿ€\13|¹„,\127bƒ¯{Ÿ~\0wX€\13|¹ƒ¯{Ÿ\127ƒq·~\0wXy…o¾~\0wX\127ƒq·{Ójûy…o¾\127ƒq·wïjîy…o¾{Ójû{jfýwïjî{Ójûx\9dþwïjî{jfýx\9dþ{jfý|Ùd\5yxa\25x\9dþ|Ùd\5yxa\25|Ùd\5ƒ@X­ƒ@X­|Ùd\5†®Zõƒ@X­†®Zõ‡†W„gULƒ@X­‡†W„gUL‡†WˆDRäƒ\24R@„gULˆDRä†$NÙƒ\24R@ˆDRä†$NÙ\127¾P ƒ\24R@†$NÙ[K…\127¾P [K…wâM¸\127¾P [K…wéHrwâM¸wéHrn¾MàwâM¸wéHrn¤Hen¾Màn¤HebœN\7n¾MàbœN\7d\18R½n¾MàbœN\7[ôT9d\18R½[ôT9]pY\22d\18R½[ôT9S©\\\21]pY\22S©\\\21U¯`ƒ]pY\22S©\\\21S@b\18U¯`ƒLq^ÅS@b\18S©\\\21Lq^ÅL~d@S@b\18Lq^ÅGf_\\L~d@L~d@Gf_\\I\29e\4Gf_\\Dãb@I\29e\4k)ŠCfãŽ;m¥ŒæjD…éfãŽ;k)ŠCjD…éj\28|ÆfãŽ;fsfãŽ;j\28|Æiûpòfsj\28|Æf\
pòfsiûpòh1l\27f\
pòiûpòcÊnHf\
pòh1l\27efi\29cÊnHh1l\27a½m5cÊnHefi\29aÊgfa½m5efi\29]¿iîa½m5aÊgf]¿iî_Hn¸a½m5]¿iî\\\1ra_Hn¸Vzrh\\\1ra]¿iî\\\1raVzrhSœzqNIyŒSœzqVzrhNIyŒO\26\127ASœzqNIyŒIÇ~\0O\26\127AO\26\127AIÇ~\0IÛ…+";
		-- Skoll
		[ 35189 ] = "w´§Ruz¤Ït¢§yw´§Rt¢§yu¨¨Îw¥2uz¤Ïw´§Rq45o¾Ÿ|s3ž¾o¾Ÿ|r•¢Ts3ž¾Ká\127ÅJ)€ÿLÆ‚:J)€ÿJõƒ•LÆ‚:P\13£¢LÓ¢nLÆ¥SP\13£¢LÆ¥SNì¥µFµ\127ÅF\
‚\12H\3€‰F\
‚\12GE‚×H\3€‰";
	};
	[ 496 ] = { -- Zul'Drak
		-- Zul'drak Sentinel
		[ 32447 ] = "HÎÑ-3×Ñu3×Ö+L~Ö$HÎÑ-3×Ö+HÎÑ-L~Ö$L’µ»Hèµ¡HÎÑ-L’µ»ik‘œeéƒeã¡©iQ¡£ik‘œeã¡©ixŒPeéƒik‘œixŒPik‘œo\26ŽÙixŒPo\26ŽÙoßˆÎoßˆÎo\26ŽÙr¶Š)r¶Š)o\26ŽÙsñæo\26ŽÙp|‘asñæsñæp|‘at¼•öp|‘aq–˜#t¼•öt¼•öq–˜#vÂ¡[t¼•övÂ¡[|\8¢×vÂ¡[{]¦‡|\8¢×vÂ¡[pH¶s{]¦‡iÁ´FpH¶svÂ¡[pH¶siÁ´F‚:Ú/pH¶s‚:Ú/„ÉÖKixŒPieƒ¢eéƒ";
		-- Griegen
		[ 32471 ] = "Dg±þ+Ú±þA|·“+Ú±þ,\1·yA|·“Dg±þA|·“F€µ\17F€µ\17A|·“@ÑÇ1=ÌÃ%@ÑÇ1A|·“=ÌÃ%3ÃÊk@ÑÇ13ÃÊk5FÏ·@ÑÇ1F»ŽßBÄŠ08†œ~<<¡£F»Žß8†œ~<<¡£8†œ~9# [E¯Š™BÄŠ0F»Žß$ê\14\" ‘'Â‘T\" ‘$ñ•Ž'Â‘T˜>dÉ•öh\3šqgÜ•öh\3˜1kJšqgÜ";
		-- Terror Spinner
		[ 32475 ] = "‹\15N¸†?N¸†8T9‹\15N¸†8T9‹\8TMiY\3›\"\\ŸŸì\\‹›\"\\Ÿ‘`4Ÿì\\‹´?L’¹^:’µ\
:\2·E7öµ\
:\2¹^:’¹^:’´?L’¸ÛM}¸ÛM}´?L’¶sOUÎBU9ÔYY\9ÔfUmÔYY\9ÎBU9Î\\\\<ÔYY\9Î\\\\<Ò3\\IÃ`iáÃMnìÈŒj\2ÈŒj\2ÃMnìÈ³sñÈ³sñÃMnìÇ1t\11¿\6¥Ï¼Iª\21Áu©Ô¼Iª\21¾Ò­¸Áu©Ô";
		-- Gondria
		[ 33776 ] = "›í—ü›¬¦ï ËŸ\13 ÿgü \19i¦¤µm« \19i¦ -t2¤µm«®ÒÁ ªÍÉ\127°ÊÁ[°ÊÁ[ªÍÉ\127®¸ÍIªÍÉ\127¬pÌž®¸ÍIÄÂ´\30É\15©ÔÅ2©JÇR§$Å2©JÉ\15©ÔÉ\15©ÔÄÂ´\30È“´”È“´”ÄÂ´\30Æš¶+° yx°\26}Š´2}—° yx´2}—´2yk¿Ä^«½¤aoÁ°ao½¤ao¿ØdSÁ°ao";
	};
	[ 606 ] = { -- Mount Hyjal
		-- Thartuk the Exile
		[ 50053 ] = "_¤:ºX´A–_å?HX´A–ZDE\11_å?H_¤:º_å?He÷>I_å?HdmAªe÷>Ie÷>IdmAªl\1M\27l\1M\27dmAªk\15PÄl\1M\27k\15PÄoùQ-k\15PÄo¾T¯oùQ-oùQ-o¾T¯sTT¨oùQ-sTT¨s¼QÊs¼QÊsTT¨uðRÞsTT¨u‡U”uðRÞuðRÞu‡U”{³W\23u‡U”z¹Yº{³W\23{³W\23z¹Yº|çYÎ{³W\23|çYÎ‚MVLAS¯{³W\23‚MVLAS¯‚MVL„ÉQ-‚ÐP\0AS¯„ÉQ-‚ÐP\0„ÉQ-…\4MÙAIe…\4MÙ„ÉQ-òFR…\4MÙAIeòFRAIe’nG¡AIe‘äKÍ’nG¡’nG¡‘äKÍ”µK¦‘äKÍ’ZQò”µK¦‘äKÍ\13QG’ZQò“FYÁ’ZQò\13QG“FYÁ\13QGÞ\\)“FYÁÞ\\)—è]}Þ\\)–š`å—è]}";
		-- Garr
		[ 50056 ] = "_Š¸r\\ô¹Ÿc\31É\15\\ô¹Ÿ`ÑÌŠc\31É\15c\31É\15`ÑÌŠg+ËÓg+ËÓ`ÑÌŠ`¾Óµ`¾Óµc\18ÖÕg+ËÓhÇÒFg+ËÓc\18ÖÕhÇÒFc\18ÖÕfzÖ>";
		-- Blazewing
		[ 50057 ] = "lí’{kx–oO’ÊoO’Êkx–tŽ—ülô\1tŽ—ükx–tŽ—ülô\1oßžBtŽ—üoßžBtÉ›Cy\127—\16tŽ—ütÉ›Cw•ŽtŽ—üy\127—\16w•Žy\127—\16z=“\11z=“\11y\127—\16~O“\24~\20\26z=“\11~O“\24~\20\26~O“\24–Â“t–Â“t~O“\24˜Ô–´–Â“t˜Ô–´™’“Ã™’“Ã˜Ô–´œà•Eœà•E˜Ô–´œô˜^œà•Eœô˜^ ª–+Ÿ“Žœà•E ª–+Ÿ“Ž ª–+£t‘:¡ë\6Ÿ“Ž£t‘:¡ë\6£t‘:¨\22²§“‡>¡ë\6¨\22²¯„§“‡>¨\22²°ë‡l§“‡>¯„°ë‡l¯„±¶‹²°ë‡l®ƒ„ã§“‡>‘T‡†–Â“t™’“Ã‘T‡†Š\28–Â“t‘T‡†:‡\3Š\28‘T‡†€Þƒê:‡\3€ÞƒêyD‹q:‡\3yD‹q{\28c:‡\3yD‹qz=“\11{\28cyD‹qw•Žz=“\11";
		-- Terrorpene
		[ 50058 ] = "~;¶§~.º’‚Ð·ü~.º’‚@»í‚Ð·ü‚Ð·ü‚@»íŒc¾‚@»í‡öÃ¨Œc¾Œc¾‡öÃ¨Ž5Ä\30‡öÃ¨‰ÇÈ\2Ž5Ä\30Ž5Ä\30‰ÇÈ\2Š\8ÎòŽ5Ä\30Š\8ÎòŒ\8ÑœŠ\8Îò„gÖ\
Œ\8Ñœ„gÖ\
…ÉÙ6Œ\8ÑœŒc¾Ž5Ä\30°Á:\13½‘Œc¾°Á:\13½‘°Á:’¶¾;’¶¾;°Á:”?Å\4°Á:’&ÆE”?Å\4";
		-- Ankha
		[ 54318 ] = "E¯€bD›„ÐJx„9D›„ÐIÛˆ7Jx„9P|„\24Jx„9IÛˆ7Jx„9P|„\24P‰\127;P‰\127;P|„\24Xy„•Xy„•P|„\24VöˆÎXy„•VöˆÎ[…Š\2VöˆÎZ^Ž¸[…Š\2[…Š\2Z^Ž¸eµŽË^v‡\
[…Š\2eµŽËfE‡^v‡\
eµŽËk6‰õfE‡eµŽËk6‰õeµŽËk\"—";
		-- Magria
		[ 54319 ] = "F%\6E\17…sJî„ÝE\17…sJQˆÛJî„ÝPò„¼Jî„ÝJQˆÛJî„ÝPò„¼Pÿ\127ßPÿ\127ßPò„¼Xï…8Xï…8Pò„¼Wl‰rXï…8Wl‰r[ûŠ¦Wl‰rZÔ\\[ûŠ¦[ûŠ¦ZÔ\\f+o^ì‡®[ûŠ¦f+of»ˆ1^ì‡®f+ok¬Š™f»ˆ1f+ok¬Š™f+ok˜Ž;";
		-- Ban'thalos
		[ 54320 ] = "BÊ™#@·óI´Ò@·óB@¢œI´ÒI´ÒB@¢œH“¢×H“¢×B@¢œEm¤ÉHR˜rBÊ™#I´ÒE¯–ÂBÊ™#HR˜r";
	};
	[ 610 ] = { -- Kelp'thar Forest
		-- Lady LaLa
		[ 49913 ] = "‘NÃ9bÆö“¶Ìà“¶ÌàbÆö\19Ì/‘NÃ9“¶Ìà¤Ý¿ì£þ»à‘NÃ9¤Ý¿ì£þ»à¤Ý¿ì¥E½c™D±n—e´\11›d²Ð›d²Ð—e´\11›à¶§›à¶§—e´\11—“·R›à¶§—“·R™Ô¸º";
	};
	[ 614 ] = { -- Abyssal Depths
		-- Poseidus
		[ 50005 ] = "j¬¿;h*Ã\11mBÃ9h*Ã\11j…ÆümBÃ9";
		-- Mobus
		[ 50009 ] = "£ä?O58üš¦I\9£ä?Oš¦I\9¢½I ¢½I š¦I\9¤ST¨¤ST¨š¦I\9œ~W†¤ST¨œ~W†¨Á]Ùœ~W†¢\5dÉ¨Á]Ù¨Á]Ù¢\5dÉ®ÒbÃ¢\5dÉªûm„®ÒbÃ®ÒbÃªûm„µLd›µLd›ªûm„µp±µLd›µp±ÀTl~»¹baµLd›ÀTl~»¹baÀTl~È7d•ÁT]²»¹baÈ7d•ÁT]²È7d•ÍBW1ÅéS‚ÁT]²ÍBW1Ï\0F»ÅéS‚ÍBW1Ï\0F»Ç1H\23ÅéS‚Ås=<Ç1H\23Ï\0F»Ì\01481Ås=<Ï\0F»Á@5tÅs=<Ì\01481Æ>,\21Á@5tÌ\01481»Ó/ÒÁ@5tÆ>,\21¾.$Ž»Ó/ÒÆ>,\21µ%-à»Ó/Ò¾.$ŽµE\"µ%-à¾.$ŽµE\"ª¹%%µ%-àª¹%%­¿/—µ%-àª¹%%¢:-Ù­¿/—¢:-Ù§š68­¿/—¢:-Ù58ü§š6858ü£ä?O§š68";
		-- Shok'sharak
		[ 50050 ] = "kJN\27h“R:nHR\25h“R:k‹V¡nHR\25ƒ÷S\5x7JáwXN¸yŒX_ƒ÷S\5wXN¸yŒX_ƒ,W\30ƒ÷S\5ƒ,W\30yŒX_|žZŸ~5F+x7Jáƒ÷S\5zçE9x7Já~5F+";
		-- Ghostcrawler
		[ 50051 ] = " ßÇš\30pÙ\2\"\25Ö§\"\25Ö§\30pÙ\2)*Þ!\30pÙ\2(€ãˆ)*Þ!4SÜÅ)*Þ!(€ãˆ1hÙk)*Þ!4SÜÅ4SÜÅ4¶Ó\0181hÙk4¶Ó\0181£Õm1hÙk.\\ÍI1£Õm4¶Ó\18.\\ÍI*\127Ï1£Õm*\127Ï.\\ÍI5‡¨“7Üª^5‡¨“.\\ÍI5‡¨“7Üª^;x¦\23;ÔŸÿ5‡¨“;x¦\23;ÔŸÿ;x¦\23=Ì òA£²\25=Ì ò;x¦\23A£²\25;x¦\23>O²Z>O²Z@ù´ÜA£²\25>O²Z<\28¹Ç@ù´Ü9\22·R<\28¹Ç>O²Z9\22·R;P¿Ä<\28¹Ç9\22·R8*Á‚;P¿Ä;P¿Ä8*Á‚@·Ð\25@·Ð\0258*Á‚?5Õ2M5ÕR@·Ð\25?5Õ2LPÐu@·Ð\25M5ÕRLPÐuM5ÕRR×Í.OËàLPÐuR×Í.R{Â¶OËàR×Í.OËàR{Â¶O;Â&R{Â¶R\12¹DO;Â&R\12¹DR{Â¶UÉ¶âUÉ¶âP\26·ÁR\12¹DUÉ¶âNì±×P\26·ÁNì±×LWº6P\26·ÁP\26·ÁLWº6M˜¾ƒLWº6G+½æM˜¾ƒDn¹¦G+½æLWº6Dn¹¦C{Æ+G+½æC{Æ+FÜÂ©G+½æFÜÂ©C{Æ+LŸÇlL¬Ã¼FÜÂ©LŸÇl ßÇš\"\25Ö§#ÐÉÇ'ÕÄÉ ßÇš#ÐÉÇ&ÂÀ– ßÇš'ÕÄÉ'ÕÄÉ0ß±Ê&ÂÀ–-æ°‚&ÂÀ–0ß±Ê0ß±Ê1u”Â-æ°‚.¿’,-æ°‚1u”Â0;\26.¿’,1u”Â0;\0261u”Â8\16‘n8\16‘n1u”Â97–\
8\16‘n97–\
;Úv9>Žv8\16‘n;Úv;Úv8ö‡È9>Žv;…„,8ö‡È;Úv9º‚a8ö‡È;…„,1\13‡\
8ö‡È9º‚a1\13‡\
0—‹À8ö‡È.ú‹\"0—‹À1\13‡\
1\13‡\
-cƒ,.ú‹\"0o„m-cƒ,1\13‡\
7»|\"-cƒ,0o„m7+wf-cƒ,7»|\"<ú{‹7+wf7»|\"<àvf7+wf<ú{‹";
	};
	[ 615 ] = { -- Shimmering Expanse
		-- Poseidus
		[ 50005 ] = "—Ò‘‚ÍóÒÒ¯ÒÒ¯‘×­—Ò—Ò‘×­•ý×º•ÜÍÌ‘‚Íó—ÒbG¦s`\6ªÚeÖ¦éeÖ¦é`\6ªÚgyªÍgyªÍ`\6ªÚ`Þ°‰`Þ°‰fm°ÑgyªÍfm°Ñ`Þ°‰cñ²¯wö€°på|çpÄ½wö€°pÄ½u›…\11rë…`u›…\11pÄ½tFy“på|çwö€°wÁ{çtFy“wö€°¥Eo\13¬\21m(¦>j³©³h ¦>j³¬\21m(¨0gÜ¦>j³©³h ¬\21m(¥Eo\13«jqª«jqª¥Eo\13¦lr°¦lr°¨ütÐ«jqª";
		-- Burgy Blackheart
		[ 50052 ] = "’\31¯ì³¼”ê³•³¼’G·\127”ê³•";
		-- Captain Florence
		[ 51071 ] = "ž¹k‹‹¼ž¼w‹‹¼ž‘¿v¼w";
		-- Captain Foulwind
		[ 51079 ] = "ˆQªd†¡­—ŠJ­w†¡­—ˆr°oŠJ­w";
	};
	[ 640 ] = { -- Deepholm
		-- Jadefang
		[ 49822 ] = "(5ã›w8Èž¾8ö›w8È\27;Pž¾8ö";
		-- Golgarok
		[ 50059 ] = "S\25ÀØQbÄŽUêÀÄR\25É\127UêÀÄQbÄŽ`ÿÍùUêÀÄR\25É\127`ÿÍùR\25É\127a‚Ü²`ÿÍùa‚Ü²f+ÖEf+ÖEa‚Ü²l‘Ûwl‘Ûwa‚Ü²mIåRl‘ÛwmIåRräãÉqøÚÚl‘ÛwräãÉqøÚÚräãÉw»×ysêÔ`qøÚÚw»×ysêÔ`w»×ywÈÓFvEÑësêÔ`wÈÓF";
		-- Terborus
		[ 50060 ] = "ŒÌ<WŠW@bi@NŠW@bŒ¿Dˆi@N";
		-- Xariona
		[ 50061 ] = "l6x\22g»tÝf\17ƒ@l6x\22f\17ƒ@k\"ƒZk\"ƒZf\17ƒ@l¿cl¿cf\17ƒ@h\16°l¿ch\16°pÄ•öh\16°lÙšûpÄ•öpÄ•ölÙšûv›ÍlÙšûtý£\18v›Ív›Ítý£\18~žó~žótý£\18~¸¥Â~žó~¸¥ÂˆÇ¡ä†öšá~žóˆÇ¡ä†öšáˆÇ¡äß™ŒŒC”\31†öšáß™ŒŒC”\31ß™Œ”gŽi|ŒÆŒC”\31”gŽi‘A‚T|ŒÆ”gŽi‘A‚T”gŽi–$œ–$œ\\vR‘A‚T“Örˆ\\vR–$œ‹]mó\\vR“ÖrˆŽÙhX‹]mó“Örˆ…8g§‹]móŽÙhX†R_å…8g§ŽÙhX~\13ez…8g§†R_å}«^\14~\13ez†R_å}«^\14uS`±~\13ezuS`±všgâ~\13ezuS`±m/gïvšgâm/gïp nƒvšgâm/gïg»tÝp nƒg»tÝl6x\22p nƒ";
		-- Aeonaxx
		[ 50062 ] = "„ð ·ƒÃ£ñˆÁ¤?„É§1ˆÁ¤?ƒÃ£ñˆÁ¤?„É§1‡R§_‡X ‰„ð ·ˆÁ¤?w8‘[v\
”•{\8”ãw\16—Õ{\8”ãv\
”•{\8”ãw\16—Õy™˜\3y ‘-w8‘[{\8”ãlí“êkÀ—$p¾—slÆšdp¾—skÀ—$p¾—slÆšdoOš’oU“¼lí“êp¾—slíu2kÀxlp¾xºlÆ{¬p¾xºkÀxlp¾xºlÆ{¬oO{ÚoUu\4líu2p¾xºt¢l<stovxroÅtzr¶xroÅstovxroÅtzr¶w\3räw\
l\14t¢l<xroÅƒ9jõ‚\12n.‡\
n}ƒ\18qo‡\
n}‚\12n.‡\
n}ƒ\18qo…›qœ…¡jÇƒ9jõ‡\
n}";
	};
	[ 700 ] = { -- Twilight Highlands
		-- Overlord Sunderfury
		[ 50085 ] = "”•T@’GX\16–ýWï’GX\16”¼[~–ýWï";
		-- Tarvus the Vile
		[ 50086 ] = "‚-Ðh€\19Ó›„`Óz€\19Ó›‚TÖ¡„`Óz";
		-- Julak-Doom
		[ 50089 ] = "–\17\0~Å\23\4‰#\24>~Å\23\4†z\30c‰#\24>‰#\24>†z\30cŽË\0270ŽË\0270†z\30c\"·ŽË\0270\"·’¢ °\25*ŽË\0270’¢ °\25*’¢ —»\17\6“þ\14æ°\25*—»\17\6";
		-- Karoma
		[ 50138 ] = "™Dmc—\23pÑ›wpo—\23pÑ™ks÷›wpoŠW†8ˆ\16‰ÍŒ‹‰áˆ\16‰ÍŠ…\27Œ‹‰á\127\26¿Ø|ÙÃ›‚Ã9|ÙÃ›\127HÇ\9‚Ã9§_—\23¤ãšç©ûšÀ¤ãšç§ržƒ©ûšÀ–fŸª“ê£É™7£©“ê£É–§§™7£©ŒcÀu‰ÍÄ‡ŽËÄt‰ÍÄ‡ŒVÈDŽËÄt";
		-- Sambas
		[ 50159 ] = "bë†‡`hŠWeŠ~`hŠWbÞŽŠeŠ~mV`4jÔdSoìd,jÔdSmIheoìd,tãK¦r3Ovw†O}r3OvtÖS¢w†O}~±8\
|„;x\25;¹|„;x~«>í\25;¹°Ä=<®ƒ@Ø³,@ì®ƒ@Ø°½D¼³,@ì";
	};
	[ 720 ] = { -- Uldum
		-- Akma'hat
		[ 50063 ] = "a[–\
_\0˜Dc{˜\9c{˜\9_\0˜Dc¸c¸_\0˜D_\13Ùc¸_\13ÙahŸì";
		-- Cyrus the Black
		[ 50064 ] = "•E™º“3œí—EœÌ“3œí•SŸì—EœÌª=¬\"¨X¯U¬<¯4¨X¯Uª6²\12¬<¯4µ®¸e³•¼5¸\22¼\21³•¼5µð¿ª¸\22¼\21•2Ñ£“MÕ$—_Õ\4“MÕ$•YØK—_Õ\4";
		-- Armagedillo
		[ 50065 ] = "rþh*påk]týk=påk]rñn5týk=";
		-- Madexx
		[ 50154 ] = "n±\26“n\0274›y\2&”y\2&”n\0274›{¹,\"{¹,\"n\0274›q\6;#n\0274›o\0078§q\6;#\127ª.—{¹,\"q\6;#|\8DZ\127ª.—q\6;#\127ª.—|\8DZ\127\0DS\127ª.—\127\0DS‹Í3¶Š6.\1\127ª.—‹Í3¶Œ</ùŠ6.\1‹Í3¶y\2&”sZ\0238n±\26“sZ\0238ov\0238n±\26“qh\21ýov\0238sZ\0238";
	};
	[ 795 ] = { -- Molten Front
		-- Skarr
		[ 50815 ] = "^\27V\30[’Z\22`ËYî[’Z\22^.]˜`ËYîUm‚ˆRë†§X\3†8Rë†§U”‰ÍX\3†8";
		-- Karkin
		[ 50959 ] = "]«Uz[\"Yr`[YK[\"Yr]¿\\ô`[YKT¼AR:…`WR„ðR:…`Tãˆ†WR„ð";
		-- Solix
		[ 54321 ] = "<”µ›à™^¢Ý”ð¢Ý”ð›à™^¤?™7›à™^¢Ýw¤?™7¢Ýw›à™^BŠBŠ AŸß¢Ýw :’{<”µ¢Ý”ð";
		-- Deth'tilac
		[ 54322 ] = "¶sµð¨Îªd§\29®Ò§\29®Ò° ½.¶sµð° ½.§\29®Òª\21¼æ´¼¤\30¨Îªd¶sµð´¼¤\30¶sµð»‹¨Œ¹á›Æ´¼¤\30»‹¨Œ¹á›Æ»‹¨Œ¾ª”\31¼B“›¹á›Æ¾ª”\31";
		-- Kirix
		[ 54323 ] = "=j§lB½²=úßGY¢œB½²=j§lGY¢œ=j§lF€¨k=j§l@[¬pF€¨kF€¨k@[¬pG†¯ìG†¯ì@[¬p>\20³gG†¯ì>\20³gC\18¹™C\18¹™>\20³g?B¹ºG†¯ìC\18¹™JD¶»JD¶»C\18¹™G\
º˜JD¶»G\
º˜KJÁnRÊ¿\6JD¶»KJÁnRÊ¿\6KJÁnNßÂ@B½²GY¢œKáš¬E¼˜ÛB½²Káš¬F\23UE¼˜ÛKáš¬F\23UKáš¬S¼“gMjŒ/F\23US¼“g";
		-- Skitterflame
		[ 54324 ] = "1:x\29.\\|¥4\11{Í.\\|¥14€:4\11{Í";
		-- Anthriss
		[ 54338 ] = ":b©ŠW^«‰\127c\25Škf‡:b©‰\127c\25Škf‡;fR:b©;fRŠkf‡Œ‘h\29\20^žŠW^«:b©Œ«]žŠW^«\20^ž";
	};
};