# -*- coding: utf_8 -*-
"""Joins Wavefront *.obj model files into a binary data file for _NPCScan.Overlay.

Instructions:
1. Run <RoutesToObjs.py> to build a folder of world map sub-folders with NPC *.obj
   files from outlines in your Routes saved variables.
2. Run this script with relevant file paths to pack resulting *.obj files into
   a Lua source file for _NPCScan.Overlay.
"""

import codecs
import os
import re
import struct

import wowdata.lua

__author__ = 'Saiket'
__email__ = 'saiket.wow@gmail.com'
__license__ = 'GPL'

class Obj(object):
  """Represents an *.obj model file to be packed for _NPCScan.Overlay."""
  _BYTES_PER_COORD = 2
  _COORD_MAX = 2 ** (8 * _BYTES_PER_COORD) - 1

  def __init__(self, filename):
    """Parses the *.obj file for vertex and face information."""
    self.vertices, self.triangles = [], []
    with codecs.open(filename, encoding='utf_8') as input:
      for line in input:
        words = line.split()
        if words:
          operator = words.pop(0).lower()
          if operator == 'v':  # Vertex
            if len(words) == 3:
              self.vertices.append(tuple(map(float, words)))
          elif operator == 'f':  # Face
            if len(words) == 3:
              # *.obj vertices are 1-indexed
              self.triangles.append(tuple(int(word) - 1 for word in words))

  def getPathData(self):
    """Returns a binary representation of this overlay's geometry."""
    bytes = []
    for triangle in self.triangles:
      for vertIndex in triangle:
        vertex = list(self.vertices[vertIndex][:2])  # Omit Z-axis
        vertex[1] = 1 - vertex[1]  # Y-axis is flipped on world map
        for coord in vertex:
          bytes.append(struct.pack('>H', round(coord * self._COORD_MAX)))  # Big-endian unsigned short
    return ''.join(bytes)


def objsToOverlays(inputPath, outputFilename):
  """Reads *.obj files from an input folder and packs them into a Lua source file."""
  inputPath, outputFilename = os.path.normcase(inputPath), os.path.normcase(outputFilename)
  print 'Packing *.obj files from <%s> to <%s>...' % (inputPath, outputFilename)

  with open(outputFilename, 'w+b') as output:
    output.write('-- AUTOMATICALLY GENERATED BY <%s>!\n' % __file__)
    output.write('select( 2, ... ).PathData = {\n')

    worldMapMatch = re.compile(r'^WorldMap(?P<id>\d+) - (?P<name>.+)$', flags=re.IGNORECASE).match
    npcMatch = re.compile(r'^Npc(?P<id>\d+) - (?P<name>.+)\.obj$', flags=re.IGNORECASE).match
    for worldMapID, worldMapName, worldMapFolder in sorted((int(match.group('id')), match.group('name'), match.string)
      for match in map(worldMapMatch, os.listdir(unicode(inputPath))) if match and os.path.isdir(os.path.join(inputPath, match.string))
    ):
      matches = [match for match in map(npcMatch, os.listdir(unicode(os.path.join(inputPath, worldMapFolder))))
        if match and os.path.isfile(os.path.join(inputPath, worldMapFolder, match.string))]
      if matches:  # At least one *.obj file
        output.write('\t[ %d ] = { -- %s\n' % (worldMapID, worldMapName.encode('utf_8')))
        print '\t%r:' % worldMapFolder
        for npcID, npcName, objFilename in sorted(
          (int(match.group('id')), match.group('name'), match.string) for match in matches
        ):
          print '\t\t%r' % objFilename
          output.write('\t\t-- %s\n' % npcName.encode('utf_8'))
          obj = Obj(os.path.join(inputPath, worldMapFolder, objFilename))
          output.write('\t\t[ %d ] = %s;\n' % (npcID, wowdata.lua.escapeData(obj.getPathData())))
        output.write('\t};\n')
    output.write('};')


if __name__ == '__main__':
  import argparse
  parser = argparse.ArgumentParser(
    description='Convert *.obj models to a Lua source file for _NPCScan.Overlay.',
    epilog=''.join((__doc__ or '').splitlines(True)[2:]),  # Duplicate file docstring's instructions
    formatter_class=argparse.RawDescriptionHelpFormatter)
  parser.add_argument('inputPath', type=unicode,
    help='Path containing *.obj models generated by RoutesToObjs.py.')
  parser.add_argument('outputFilename', type=unicode,
    help='Output path for the resulting Lua source file.')
  objsToOverlays(**vars(parser.parse_args()))