-- AUTOMATICALLY GENERATED BY <_NPCScan.Tools/Tools/RoutesToPathData.lua>!
select( 2, ... ).PathData = {
	[ 614 ] = { -- Abyssal Depths
		-- Ghostcrawler
		[ 50051 ] = "-æ°‚.¿’,0;8ö‡È0—‹À.ú‹\"-cƒ,7+wf<àvf<àvf<ú{‹7»|\"1\r‡\
9º‚a;…„,;…„,;Úv97–\
0ß±Ê'ÕÄÉ#ÐÉÇ5‡¨“;ÔŸÿ=Ì ò=Ì òA£²@ù´ÜOËàO;Â&R¹DP·ÁM˜¾ƒG+½æFÜÂ©L¬Ã¼LŸÇlR{Â¶R×Í.M5ÕR?5Õ28*Á‚9·RpÙ ßÇš&ÂÀ–-cƒ,<àvf7»|\"FÜÂ©LŸÇlC{Æ+UÉ¶âR{Â¶M5ÕR-cƒ,7»|\"0o„mG+½æFÜÂ©C{Æ+.ú‹\"-cƒ,0o„mG+½æC{Æ+Dn¹¦.ú‹\"0o„m1\r‡\
G+½æDn¹¦LWº68ö‡È.ú‹\"1\r‡\
P·ÁG+½æLWº68ö‡È1\r‡\
;…„,P·ÁLWº6Nì±×9>Žv8ö‡È;…„,R¹DP·ÁNì±×9>Žv;…„,97–\
R¹DNì±×UÉ¶â8‘n9>Žv97–\
OËàR¹DUÉ¶â0;8‘n97–\
OËàUÉ¶âM5ÕR0;97–\
1u”ÂLPÐuOËàM5ÕR-æ°‚0;1u”Â@·ÐLPÐuM5ÕR-æ°‚1u”Â0ß±Ê@·ÐM5ÕR?5Õ2&ÂÀ–-æ°‚0ß±Ê;P¿Ä@·Ð?5Õ2&ÂÀ–0ß±Ê#ÐÉÇ;P¿Ä?5Õ29·RpÙ&ÂÀ–#ÐÉÇ<¹Ç;P¿Ä9·RpÙ#ÐÉÇ\"Ö§@ù´Ü<¹Ç9·R(€ãˆpÙ\"Ö§@ù´Ü9·R>O²Z(€ãˆ\"Ö§)*Þ!=Ì ò@ù´Ü>O²Z4SÜÅ(€ãˆ)*Þ!=Ì ò>O²Z;x¦4SÜÅ)*Þ!1hÙk5‡¨“=Ì ò;x¦4¶Ó4SÜÅ1hÙk5‡¨“;x¦7Üª^4¶Ó1hÙk1£Õm*Ï5‡¨“7Üª^.\\ÍI4¶Ó1£Õm*Ï7Üª^.\\ÍI1£Õm*Ï.\\ÍI";
		-- Mobus
		[ 50009 ] = "ª¹%%µE\"¾.$Ž¾.$ŽÆ>,Ì81Ì81Ï\000F»ÍBW1ÍBW1È7d•ÀTl~ÀTl~µp±ªûm„ªûm„¢dÉœ~W†œ~W†š¦I	¢½I £ä?O¢½I š¦I	š¦I	58ü¢:-Ù¢:-Ùª¹%%¾.$Ž¾.$ŽÌ81ÍBW1ÍBW1ÀTl~ªûm„œ~W†¢½I ¤ST¨§š68£ä?Oš¦I	ªûm„œ~W†¤ST¨§š68š¦I	¢:-Ùªûm„¤ST¨¨Á]Ù­¿/—§š68¢:-Ùªûm„¨Á]Ù®ÒbÃµ%-à­¿/—¢:-Ùªûm„®ÒbÃµLd›µ%-à¢:-Ù¾.$Žªûm„µLd›»¹ba»Ó/Òµ%-à¾.$ŽÍBW1ªûm„»¹baÁ@5t»Ó/Ò¾.$ŽÍBW1»¹baÁT]²Ås=<Á@5t¾.$ŽÍBW1ÁT]²ÅéS‚Ås=<¾.$ŽÍBW1ÍBW1ÅéS‚Ç1HÍBW1Ç1HÅs=<";
		-- Poseidus
		[ 50005 ] = "h*Ãj¬¿;mBÃ9mBÃ9j…Æüh*Ã";
		-- Shok'sharak
		[ 50050 ] = "h“R:kJNnHRnHRk‹V¡h“R:yŒX_wXN¸x7Jáx7JázçE9~5F+~5F+ƒ÷Sƒ,Wƒ,W|žZŸyŒX_yŒX_x7Já~5F+~5F+ƒ,WyŒX_";
	};
	[ 475 ] = { -- Blade's Edge Mountains
		-- Hemathion
		[ 18692 ] = "J’¢nM] hO5¢O5¢ST´ÖL»ÚL»ÚHè¹WFRªáFRªáFý¦âJ’¢nJ’¢nO5¢L»ÚL»ÚFRªáJ’¢nIº€ëJûsOØoùOØoùQ°r3P¾|6RTÑUÉ…ŽU÷iU÷iQ‘ÿJŒ…ÉJŒ…ÉIº€ëOØoùP¾|6RTÑU÷iJŒ…ÉOØoùP¾|6P¾|6U÷iJŒ…É";
		-- Morcrush
		[ 18690 ] = "˜r7Âœô1–Ÿ3ZŸ3Z ò9lŸ=Æ›ÓA™™C½–A:–A:–>;˜r7Â˜r7ÂŸ3ZŸ=ÆŸ=Æ›ÓA–A:Ÿ=Æ–A:˜r7Â­BÃZ«¬£®OŸ4®OŸ4±-¢²¯Â¢²¯Â¢°Å®­BÃZ®OŸ4²¯Â¢­BÃZ ÿ‰ £ŒV£•‹\"µÖe?¶K¹¸ÁC¸ÁC½Š;~Áñ9 Ç>:7Ì\"E‡ÉáG€¸“MB¸Xf¶ÈiD²½k~«‚©¤ãŽŠ¤ãŽŠ ÿ‰£•‹\"Ç>:7ÉáG€Åã=w¤ãŽŠ£•‹\"¨è€°Áñ9 Ç>:7Åã=w²½k~¤ãŽŠ¨è€°Áñ9 Åã=wÂ=²½k~¨è€°± hyÁñ9 Â=¾ƒ>²¶ÈiD²½k~± hy¸ÁCÁñ9 ¾ƒ>²¶ÈiD± hyµÖe?¸ÁC¾ƒ>²º¬Eð¸“MB¶ÈiDµÖe?¸ÁCº¬Eð¸“MBµÖe?¸ÁC¸“MB";
		-- Speaker Mar'grom
		[ 18693 ] = "e¼‚ëi=zŒmàxïmàxïoÅ|o4‰­o4‰­lÓ‘nfÕ•zfÕ•zdê“e¼‚ëe¼‚ëmàxïo4‰­o4‰­fÕ•ze¼‚ë\\BëË?¸•‡K•‡K•ðQ4Žæ`vŽæ`vŒI]/’P’ML¹\\Bë•‡K•‡KŽæ`v’P•‡K’P’ML¹¢¢/—¥€,Ó¨¦/(¨¦/(¯@.­—F\
­—F\
«dF¦é?±¦é?±¢4¢¢/—¢¢/—¨¦/(­—F\
­—F\
¦é?±¢¢/—lÎiqhÁ°t`¿4t`¿4vé¿ËxïÄSxïÄSy…ÈÁxlËÌxlËÌmBÖÎjºÕöjºÕöj^ÒÐlÎilÎit`¿4xïÄSxïÄSxlËÌjºÕöxïÄSjºÕölÎi";
	};
	[ 486 ] = { -- Borean Tundra
		-- Fumblub Gearwind
		[ 32358 ] = "£t'L¨ *=±-2ÿ±-2ÿ¬:eª5FŸ|<Ÿ¢@A¤?H¢×SGª‹WR®![d³9S{¯vOƒ®JÇ®JÇ¬:e±-2ÿ±-2ÿ¸;¸ü>¤¸ü>¤¶Á@·²{@N¸>M²¹…GÏ»ÆE`»ÆE`½cG€½ÌR:½ÌR:¼ZD¸¦aÿ¸¦aÿ®«cþžó[‹žó[‹„Xš\\Rn›wD¶˜lGl–\
D¨–\
D¨–L;^˜e0±˜e0±™­#ˆ›Ó\"°›Ó\"°£t'L±-2ÿ±-2ÿª5F¤F0ØŸ|<Ÿ¤?H¢×SG±-2ÿ¸ü>¤²{@N¸>M²»ÆE`½ÌR:¸¦aÿžó[‹\\Rn›wD¶–\
D¨˜e0±›Ó\"°±-2ÿ¤F0Ø±-2ÿ²{@N°òCµÏO!¸>M²½ÌR:OEz›wD¶˜e0±˜e0±›Ó\"°¤F0Ø®JÇ±-2ÿ°òCµÏO!½ÌR:¸¦aÿ˜e0±¤F0Ø A71³9S{®JÇ°òC³LŸµÏO!¸¦aÿOEz˜e0± A71³9S{°òC±ÞIk±ÞIk³LŸ¸¦aÿOEz A71Ÿ|<Ÿ³9S{±ÞIk¸¦aÿžpJkOEzŸ|<Ÿ±äXÈ³9S{¸¦aÿžpJkŸ|<Ÿ¢×SG®![d±äXÈ¸¦aÿ\\RnžpJk¢×SG®![d¸¦aÿ\\Rn¢×SG®![d\\Rn";
		-- Icehorn
		[ 32361 ] = "ÌÙyÌút¼ÚÚuÚÚuÛy ÌÙyÜIV”ì!PNí.TÉÜ\"[’Î}PòÐMÜIV”í.TÉÜ\"[’ÜIV”Ü\"[’ÐMâgiQà-f+âMb¶âMb¶äzeéâgiQ";
		-- Old Crystalbark
		[ 32357 ] = "4Lq5SC¯9áC¢I™Q'N(K^Q-KXïEýV¡C{U?;U?;V;0Z#?¸Z#?¸\\\"Cˆ[‹L[‹LT`TRTUSIrW€>^7¡XÁ4Lq9áC¢8âJ™I™Q'Q-KU%OåXïEýU?;Z#?¸[‹LRTUSIrW€7¡XÁ4Lq8âJ™AoUðI™Q'U%OåW†M]XïEýZ#?¸7¡XÁ8âJ™;#S3W†M]Z#?¸[‹L7¡XÁ;#S3AoUðU%OåW†M][‹LIrW€7¡XÁAoUðU%Oå[‹LIrW€AoUðU%OåIrW€";
	};
	[ 640 ] = { -- Deepholm
		-- Aeonaxx
		[ 50062 ] = "uÂaT~^±†Â`‰†Â`‰Hhü”Fs,”Fs,–”‚@”Ö\r”Ö\rNš0‰7¢ˆ‰7¢ˆ'¦fum£¶um£¶mI›Ÿh‘Th‘Tf€ƒäh*uh*ul¥xºk’ƒþpo'l¥xºh*uh*umžh“uÂaTh‘Th*uk’ƒþw\
h†po'h*uh‘Tk’ƒþm/Žw\
h†h*uuÂaTum£¶h‘Tm/Ž~}fw\
h†uÂaTum£¶m/Žq4–š…¨hK~}fuÂaTum£¶q4–švýœp…¨hKuÂaT†Â`‰‰7¢ˆum£¶výœp‹Ín—…¨hK†Â`‰‰7¢ˆvýœp\rž—Ëvö‹Ín—†Â`‰‰7¢ˆ\rž—‡e›…Ëvö†Â`‰”Fs,”Ö\r‰7¢ˆ‡e›…‘°‚øËvö”Fs,”Ö\r‡e›…Œ²”Â‘°‚ø”Fs,”Ö\r”Ö\rŒ²”Âìj”Ö\rìj‘°‚ø";
		-- Golgarok
		[ 50059 ] = "O¤Ç	Xâ·š[¬·§[¬·§\\ºŸZ0Ã@`ËÊçf\
Ïf+ÖEjîÙQn‘Õ¨q[ÕRq[ÕRy¦ÖÕ{ûÙD{ûÙD{Cãˆy³çQy³çQsêæ>mäfmäfc,ß|YõØYõØRÃÐªNóËNóËO¤Ç	[¬·§Z0Ã@`ËÊçf+ÖEjîÙQq[ÕR{ûÙD{ûÙDy³çQmäfmäfYõØNóËNóË[¬·§Z0Ã@jîÙQ{ûÙDmäfmäfNóËZ0Ã@f+ÖEjîÙQmäfZ0Ã@f+ÖEmäf";
		-- Jadefang
		[ 49822 ] = "›w8È(5ãž¾8öž¾8ö;P›w8È";
		-- Terborus
		[ 50060 ] = "†?@bŒ/<Ž—=<Ž—=<Ž!@ª‡ Dˆ‡ Dˆ†C3†?@bŽ—=<‡ Dˆ†?@b";
		-- Xariona
		[ 50061 ] = "uS`±}«^†R_å†R_åŽÙhX“Örˆ“Örˆ–$œ”gŽi”gŽiß™ŒˆÇ¡äˆÇ¡ä~¸¥Âtý£tý£lÙšûh°h°fƒ@g»tÝg»tÝl6xk\"ƒZp nƒl6xg»tÝg»tÝm/gïuS`±h°g»tÝk\"ƒZvšgâp nƒg»tÝh°k\"ƒZl¿cvšgâg»tÝuS`±tý£h°l¿c~\rezvšgâuS`±tý£l¿cpÄ•ö…8g§~\rezuS`±tý£pÄ•öv›Í…8g§uS`±†R_åˆÇ¡ätý£v›Í‹]mó…8g§†R_åˆÇ¡äv›Í~žó\\vR‹]mó†R_åˆÇ¡ä~žó†öšá\\vR†R_å“Örˆ”gŽiˆÇ¡ä†öšá‘A‚T\\vR“Örˆ”gŽi†öšáŒC”‘A‚T“Örˆ”gŽi”gŽiŒC”|ŒÆ”gŽi|ŒÆ‘A‚T";
	};
	[ 488 ] = { -- Dragonblight
		-- Crazed Indu'le Survivor
		[ 32409 ] = "%÷”Â3ŠÚ=†=†?'‡»HÈšáJ…šMw“ÉUýUýW$’OU—ÛOU—ÛKk H¡@4S4'R™^%÷”ÂJ…šUýOU—Û<íŒc4S4%÷”ÂJ…šOU—ÛH¡@<íŒc%÷”Â=†HÈšáJ…šH¡@H¡@<íŒc=†=†HÈšáH¡@%ŽwR%Ép¾(Õoª(Õoª+)yk) {/(Õoª) {/%ŽwR";
		-- Scarlet Highlord Daion
		[ 32417 ] = "³•7Üµ®2‚¸á9Á¾ANÄ¯F”ÃSHâÃSHâ¼/G”¶§C@¶§C@³•7Ü¸á9Á¸á9Á¾ANÃSHâ¸á9ÁÃSHâ¶§C@Ü}m˜ÚW\\~Û¹YáÛ¹Yáá£YÎâ¢[çâ¢[çß‰n!Ü}m˜Û¹Yáâ¢[çÜ}m˜¶ü·R¶´­¿¸è­ß¹r»w»ÌÀGº’Áø²øÀA±@Æs¯|Å®¯|Å®±n½V´Ï¸Q¶ü·R¸è­ß¹r»w¹r»wº’Áø·¾²øÀA¯|Å®´Ï¸Q´Ï¸Q¶ü·R¹r»w¹r»w·¾µ\
½Oµ\
½O²øÀA´Ï¸Q¹r»wµ\
½O´Ï¸Q";
		-- Tukemuth
		[ 32400 ] = "™JTÖ˜§I†œ/HÁœ/HÁ\\Uã–ýj	Iyûœ‹l¿¢&\\¯ÿKx©ŒO!¨™I†¨™I†°E¼³ÝHK³ÝHK·LŸ·rTZ·rTZµ®X®ù\\C¯rGµ~\\µÖˆ^µÖˆ^­Oªš²t€Þ¬žuª~k~ o£SŠ0 o–´ o–´œ¿ž±˜§Ÿå˜§Ÿå”,™Í–¡‘[”ÉŽ¾–¡‘[”,™Í‘‰7ŠWš¦‡“˜X‡“˜XŽÙ„z“,yx“,yx“n¸“©h7™JTÖœ/HÁ–ýj	¯ÿKx¨™I†³ÝHKµÖˆ^ªš²Z†€²t€Þª~k~¨Ôb× o–´˜§Ÿå–¡‘[”‡‰e”ÉŽ¾”,™Í‘‰7‡“˜X“,yx“,yx“©h7™JTÖ™JTÖ–ýj	–>ph³ŽO'¯ÿKx³ÝHKµÖˆ^²Z†€²t€Þ o–´–¡‘[™³’½”‡‰e”,™Í‘‰7‘‰7“,yx™JTÖ³ŽO'³ÝHK·rTZ¯rGµÖˆ^²t€Þ o–´™³’½œ‹‘‰–\
…+”‡‰e‘‰7‘‰7™JTÖ–>ph³@S,³ŽO'·rTZ«ú`ì¯rG²t€Þ o–´œ‹‘‰ž\\—–\
…+‘‰7–>ph­žV³@S,·rTZ«ú`ì²t€Þ¨Ôb× o o–´ž\\—–\
…+–>ph–âyº¢&\\­žV·rTZ®ù\\C«ú`ì¨Ôb× ož\\—óˆ*˜Ôƒ¯–\
…+–âyº¢&\\·rTZ®ù\\C®ù\\C¨Ôb×¦»`U oóˆ*œC„¢œC„¢˜Ôƒ¯–âyº¢&\\®ù\\C¦»`UœC„¢–âyº™=|‹¢&\\¦»`U¤‡`œC„¢™=|‹Iyû¢&\\¤‡` o oœC„¢IyûIyû¢&\\ o";
	};
	[ 490 ] = { -- Grizzly Hills
		-- Arcturis
		[ 38453 ] = "Ni’MNBBQåBQåBQÊ’@Ni’M";
		-- Grocklar
		[ 32422 ] = "ÓuÁjW*f8*f8Ídz«f_!ër'yÛ(1€o(1€o'R\r%S’,%S’,¹“¼Æ‘aÓu*f8«f_!ër(1€o%S’,%S’,Æ‘ažòžòÓu«f_«f_!ër%S’,žò«f_%S’,Q·’³M\"Ê²×\"Ê²×(X¯A+¬°½2G¶†9“¶E;…½\\;…½\\:	¿b.»Ú)­¶%9¶lQ·Q·\"Ê²×+¬°½2G¶†;…½\\.»Ú)­¶Q·+¬°½+¬°½2G¶†.»Ú+¬°½.»Ú)­¶3¢Ä5SB<Ú‰À<Ú‰ÀB ˆ§D%‹)D%‹)DM–ÜBT™xBT™x5êšÚ3Ã–Ü3Ã–Ü3¢Ä<Ú‰À<Ú‰ÀD%‹)BT™x<Ú‰ÀBT™x3Ã–ÜHKn¾Fk‹HRh*HRh*J…k=HKn¾";
		-- Seething Hate
		[ 32429 ] = "C,vfDq[H†r•H†r•I#vâDÐz’H†r•DÐz’C,vfW$zW[]{/[=|[=|Y	‚ˆU`[=|U`W$zWd9yºhz’i ¤i ¤fð„a£€Øa£€ØaN|úd9yºi ¤a£€Ød9yº";
		-- Syreian the Bonecarver
		[ 32438 ] = "¥öTÝ¦K­ÅB­ÅB¯ª=w±n=æ±n=æ²T?ù± D¯´M¿ºCR¾.Y¦¾ìaoÂ©`ÄÄcˆÄcˆÅ2lÓ¾ƒqN¾ƒqN¼¸pH»Æjx¹îbþ°S©­æLC©™Vð¬¥\\q­waÿ­waÿ­kÚ«nO«nO§kî§dÃ¦^BŸªb:„`\r„`\r›çXÈžvW§­ÅB±n=æ± D¯´M¿¾.Y¦¾ìao¾ìaoÄcˆ¾ƒqN¾ƒqN»Æjx¹îbþ©™Vð­waÿ«nO«nO§dÃ¦^B„`\ržvW§ Ë[³­ÅB± D¯°£Hâ°£Hâ´M¿¾ìao¾ìao¾ƒqN¹îbþ©	M¿©™Vð«nO¦^B„`\r Ë[³°£Hâ¾ìao¹îbþ©	M¿«nO¦^B¦^B Ë[³£êY™­ÅB°£Hâ¹îbþ¦^B£êY™¥öTÝ­ÅB¹îbþ­æLC©	M¿¦^B¥öTÝ­ÅB­æLC¬/K©	M¿¥öTÝ­ÅB­ÅB¬/K©	M¿";
	};
	[ 465 ] = { -- Hellfire Peninsula
		-- Fulgorge
		[ 18678 ] = "<q¦>:0“@?;u÷?;u÷E›kLeSLeSN}YQ£ZkQ£ZkNÅhlG€o·>“g@!¤É<q¦>LeSQ£ZkG€o·>“g<q¦>?;u÷?;u÷LeSG€o·B‰x´>“g?;u÷?;u÷G€o·B‰x´IÛ±‚FL²FÜ©ŒFÜ©ŒJº¢¯Q:™ûX1“tY“Š\\à„ã\\à„ãc&€–kJ€Ëp£}ós¶z~u”~žu”~žr3ƒl\"†8[6‘ÿYîšÚWŸåJ…ª…IÛ±‚FÜ©ŒFÜ©ŒQ:™ûV?™ÍV?™ÍX1“t\\à„ãkJ€Ëp£}óu”~žu”~žl\"†8cþ†ÜMc¥µJ…ª…FÜ©Œ\\à„ãkJ€Ëu”~žQÞŸùMc¥µFÜ©Œ\\à„ãu”~žcþ†ÜQÞŸùFÜ©ŒV?™Í\\à„ãcþ†Ü]I‹çWŸåQÞŸùV?™ÍV?™Í\\à„ã]I‹ç[6‘ÿWŸåV?™ÍV?™Í]I‹ç[6‘ÿf®¸Áfs¥¨jd¥Èm/¶1t¢¯±zÔ¯å²µ—´µ—º—ºÌºkz^¶_u¨¶Yqø¹l»‹f®¸Ájd¥Èj6´gm/¶1zÔ¯å²µ²µ—ºz^¶_u¨¶Yl»‹f®¸Áf®¸Áj6´gm/¶1m/¶1²µz^¶_u¨¶Yf®¸Ám/¶1m/¶1z^¶_u¨¶Y";
		-- Mekthorg the Wild
		[ 18677 ] = "rÊsqœmcsnh1snh1vh>w§k˜~\\~žŠ~ÙŽ;‚nŽ;‚nƒ‡´‰k{’½vÜœÙr&ž±k=´zjŸ¸>hü·´hü·´ie³Fk‹¢‚k‹¢‚pH—yru”ÏvxrsTu2rÊsrÊssnh1w§k˜~\\~žŽ;‚n‰k‰k{’½r&ž±oO¢ak=´zhü·´hü·´k‹¢‚ru”ÏvxrrÊsw§k˜|¿}\"~\\~ž‰k‰kr&ž±oO¢aoO¢ahü·´ru”Ïz’„ãvxrw§k˜w§k˜|¿}\"‰koO¢aru”ÏuÜ•Ïz’„ãw§k˜‰k‰koO¢auÜ•Ïzû‰z’„ã‰k‰kuÜ•Ïzû‰¬\"Çè¤LÀu¢ä½Ù¢ä½Ù£¯µR¥»²•¥»²•¯¾®U±Ñ¯.±Ñ¯.¶öµµ·¹J°½½®pÆy¬\"Çè¬\"Çè¢ä½Ù¥»²•¥»²•±Ñ¯.·¹J°½½¬\"Çè¥»²•¥»²•·¹J²Ýº¥»²•²Ýº°½½";
		-- Vorakem Doomspeaker
		[ 18679 ] = "†lFE‡üC¯˜ÁL]ŸKÓ¥LH­¨áJD¨áJD©áO—§üRa§üRa¤RÑˆMˆM†lFE˜ÁL]ŸKÓ¨áJD§üRa§üRaˆM˜ÁL]˜ÁL]ŸKÓ§üRa²ax	¯Nr°°ëov¹Jg¡º¦aë½^ž½^ž¿Ëao¿'gK¿'gK¹õw1¶syX¶syX²ax	°ëov¹Jg¡½^ž¿'gK¶syX°ëov³ãoØ³ãoØ¹Jg¡¿'gK³ãoØ¿'gK¶syX³¯ùµˆ§º=‰Àº=‰À¾\r’ë¾!˜Î¾!˜Îº³œ²¸7š™¸7š™³¯ùº=‰Àº=‰À¾!˜Î¸7š™a'NžcKkIXkIXo.L²mžTMmžTMjkUÂc©T@c©T@a'NžkIXkIXmžTMc©T@";
	};
	[ 491 ] = { -- Howling Fjord
		-- King Ping
		[ 32398 ] = "O!(ST“¯PA—PA—M/ŽžO!(FfŸFµ¤ãCa¦fCa¦f>¥S>I¢ÐCa¦f>I¢ÐFfŸMÌ½5N¿¯ìPì°Pì°P\r½¸MÌ½5QN½\000S,½RëÄRëÄQÃþQN½\000QåÏSaÉ¬W†ÉW†ÉWšÌjSˆÑW†ÉSˆÑQåÏ";
		-- Perobas the Bloodthirster
		[ 32377 ] = "€·‚u	ˆDˆD‹Ÿ/Š)\"TŠ)\"TˆK!ÿ‚ˆå‚ˆåªß€·€·ˆDŠ)\"TŠ)\"T‚ˆå€·—š3G˜Û.Ò¤2[¤2[›w9Œ™ :D¤2[™ :D—š3GªC.¿¬I'\
®Ë%F³&Ž¶§Ì¸>˜¸>˜¹À#·Á*è±{+W¬p0ªªC.¿ªC.¿®Ë%F³&Ž³&Ž¸>˜·Á*è±{+WªC.¿³&Ž³&Ž·Á*è±{+W";
		-- Vigdis the War Maiden
		[ 32386 ] = "¯·~¾®!u¨¯ØpÄµ€n—¹xe»¬b{½vemÀe?Â{hÕÂ{hÕÃãsÃ€ÀëßÁž½‘¡u½‘¡u¹³Ÿù¶®›<³g™=­¤–»­Ì“g´t„ð¯·~¾¯ØpÄµ€n—»¬b{½vem½vemÂ{hÕÃ€ÁˆõÀëß½‘¡u¶®›<³g™=­Ì“g´t„ð¯ØpÄµ€n—µ€n—½vemÃ€Áˆõ½‘¡u¶®›<¶®›<­Ì“g±:“t´H´t„ðµ€n—µ€n—Ã€ÁˆõÁˆõ¶®›<±:“t´Hµ€n—ÁˆõÁˆõ±:“t´H";
	};
	[ 492 ] = { -- Icecrown
		-- High Thane Jorfus
		[ 32501 ] = "­ßg´¬²b©­«]p­«]p°‰ZÇµ\
\\/»W¡½;Oi¿ËPo¿ËPo½Z^¶â_.¶â_.¶Èf´iõ´iõ°Aj­ßg´­ßg´­«]pµ\
\\/»W¡¿ËPo¶â_.¶â_.´iõ­ßg´­ßg´µ\
\\/»W¡»W¡¶â_.­ßg´|PáavðÛqxXÇÁxXÇÁzûÅ_òËòËÒàA|PáaxXÇÁòË|PáaN›…PòœÌPN¡©S©°:\\d°½]„³›]„³›\\d¶+P–µãP–µãOƒ³ZPA¯PA¯M uN›…N›…PN¡©S©°:S©°:]„³›P–µãPA¯N›…S©°:S©°:P–µãPA¯";
		-- Hildana Deathstealer
		[ 32495 ] = "JqÞHXu¨HRdðLçTIÛL¥JJF¡JJF¡MAªQÄB ]Ó?\r]p<j_:Ô_:Ô`ò<ç`@\000`@\000^(DŽUtIÁM}N‘P.S¶N.]O` RdtS9ieS9ieR&nìL²uIÎwöEê}ODÝ{ŸHXu¨JqÞNÒmVJºfRJqÞHRdð]B3]Ó?\r_:ÔLIJÇM}N‘N.]S9ieL²uIÎwöIÎwöDÝ{ŸHXu¨LŸb×JºfRHRdð]B3_:Ô`@\000S9ieIÎwöHXu¨LŸb×HRdðK)]„]B3`@\000UtIÁS9ieHXu¨NÒmVO¾hšLŸb×K)]„U¨FÜ]B3UtIÁS9ieNÒmVO¾hšO¾hšK)]„LçTQÄB U¨FÜUtIÁO` S9ieO¾hšQÄB UtIÁP±EêN.]O` O¾hšQÄB P±EêMóEÂN.]O¾hšLçTJJF¡QÄB MóEÂLIJÇN.]LçTJJF¡MóEÂLIJÇLçTJJF¡LIJÇ†\
ŽB†Š~ˆr‡Áˆr‡Á‹„ŽÒ„2’äŠû—ü‡§™‰Í–öÞš6—R™’ú™’ú—E ò“M¡£“M¡£“Ðžv–öp‰*Šô‡§²†\
ŽB†\
ŽBˆr‡ÁŽÒ„2’äŠû™‰Í–öÞ™’ú“M¡£–öp‹¬ˆ1‰*Šô†\
ŽB’äŠû–öÞ™’ú™’ú–öp—˜K‹¬ˆ1†\
ŽBŽÒ„2’äŠû™’ú—˜KŽUˆr‹¬ˆ1ŽÒ„2ŽÒ„2’äŠû—˜KŽÒ„2—˜KŽUˆr";
		-- Putridus the Ancient
		[ 32487 ] = "°ë³­ì¯ì­«©xv?•{P¬žwé®wé®rh•›r×ˆDr×ˆDwE{˜‚f®‚f®ŠkaÄ˜ºct§>s¼®—“²@¦f²@¦f³Ö©*´,°´,°°ë³­«©xv?•wé®r×ˆD§>s¼²@¦f´,°´,°­«©x®±§ev®‰Œv?•r×ˆD§>s¼´,°®±§ezv®‰Œr×ˆD§>s¼®±§e«\"•€ƒäkôzr×ˆD§>s¼«\"•€¤`y*ƒäkôr×ˆD‚f®˜ºct§>s¼¤`y*ŠxgÎƒäkô‚f®˜ºct¤`y*–ýh´–ýh´ŠxgÎ‚f®–ýh´‚f®˜ºct";
	};
	[ 610 ] = { -- Kelp'thar Forest
		-- Lady LaLa
		[ 49913 ] = "bÆö‘NÃ9£þ»à£þ»à¥E½c¤Ý¿ì¤Ý¿ì“¶ÌàÌ/Ì/bÆö£þ»à£þ»à¤Ý¿ìÌ/—e´™D±n›d²Ð›d²Ð›à¶§™Ô¸º™Ô¸º—“·R—e´›d²Ð™Ô¸º—e´";
	};
	[ 606 ] = { -- Mount Hyjal
		-- Blazewing
		[ 50057 ] = "kx–lí’{oO’ÊŸ“Ž¡ë§“‡>§“‡>®ƒ„ã°ë‡l°ë‡l±¶‹²¯„£t‘: ª–+œô˜^œô˜^˜Ô–´–Â“t~–Â“t˜Ô–´y—tÉ›CoßžBoßžBlôkx–kx–oO’ÊtŽ—üŸ“Ž§“‡>°ë‡l°ë‡l¯„¨²œô˜^–Â“tŠ~˜Ô–´~O“~O“y—oßžBoßžBkx–tŽ—üŸ“Ž°ë‡l¨²z=“~~O“~O“oßžBtŽ—üŸ“Ž¨²£t‘:~O“tŽ—üw•Žœà•EŸ“Ž£t‘:z=“~O“w•Žœà•E£t‘:œô˜^{cz=“w•Ž™’“Ãœà•Eœô˜^{cw•ŽyD‹q™’“Ãœô˜^Š:‡{cyD‹q‘T‡†™’“ÃŠ:‡yD‹q€Þƒê€Þƒê‘T‡†Š€ÞƒêŠ:‡";
		-- Garr
		[ 50056 ] = "cÉg+ËÓhÇÒFhÇÒFfzÖ>cÖÕcÖÕ`¾Óµ`ÑÌŠ`ÑÌŠ\\ô¹Ÿ_Š¸rcÉhÇÒFcÖÕcÖÕ`ÑÌŠ_Š¸rcÉcÖÕ_Š¸r";
		-- Terrorpene
		[ 50058 ] = "ŠÎòŒcÁ°\r½‘\r½‘’¶¾;”?Å”?Å’&Å¨°Á:ŒÑœ…ÉÙ6„gÖ\
\r½‘”?Å°Á:ŒÑœ„gÖ\
ŠÎò\r½‘°Á:Ž5ÄŽ5ÄŒÑœŠÎò\r½‘Ž5ÄŠÎò…¡½Ù€[¹kn¶\
n¶\
†Ïº¦…¡½Ù";
		-- Thartuk the Exile
		[ 50053 ] = "oùQ-s¼QÊuðRÞAS¯‚ÐP\000…MÙ…MÙòFR’nG¡’nG¡”µK¦’ZQò“FYÁ—è]}–š`åÞ\\)\rQG‘äKÍ„ÉQ-‚MVL|çYÎ|çYÎz¹Yºu‡U”sTT¨o¾T¯kPÄdmAª_}>«_¤:ºoùQ-uðRÞ{³W“FYÁ–š`åÞ\\)u‡U”sTT¨kPÄdmAª_¤:ºe÷>I’ZQò“FYÁÞ\\)kPÄdmAªe÷>I’nG¡’ZQòÞ\\)kPÄe÷>IlM’nG¡Þ\\)‘äKÍkPÄlMoùQ-’nG¡‘äKÍAIeu‡U”kPÄoùQ-…MÙ’nG¡AIe|çYÎu‡U”oùQ-…MÙAIe„ÉQ-|çYÎoùQ-{³WAS¯…MÙ„ÉQ-|çYÎ{³WAS¯AS¯„ÉQ-|çYÎ";
	};
	[ 477 ] = { -- Nagrand
		-- Bro'Gaz the Clanless
		[ 18684 ] = "Qå;‹UÖ9DWÁ>WÁ>XREêVsQVsQT,XMYH1`FzD›AAª„•A‹6>¸‹Æ>¸‹Æ>í„AÞ}ÅCTyE]žGÕWRJºQÿCÃQå;‹Qå;‹WÁ>VsQH1`D›AAª„•Aª„•>¸‹ÆAÞ}ÅRJºQå;‹VsQAª„•AÞ}ÅCTyNæPØRJºVsQH1`Aª„•CTyGÕWNæPØVsQH1`CTyGÕWGÕWVsQMYIõ\\ŸH1`GÕWMYIõ\\ŸGÕWnŽUm\"ˆ^t%‰Àt%‰Àt›ŒIs3ŽÅuY“¯{\"—­}5šç†¡‡Û·‡ö\r…Ü\r…Ü~ó‚Zƒ3ƒþ‡*ƒÝŒ6[Œ~„µ‰Ç‹’‰7•S‡ï›C…¨ŸÄ…¤z€|¦f€|¦f|ž¦y{ç by³œt¼˜ÁnŽUnŽUt%‰Às3ŽÅ†¡‡Û\r…Üƒ3ƒþƒ3ƒþ‡*ƒÝŒ~„µ‰Ç‹’‡ï›C…¨ŸÄ…¨ŸÄ€|¦f{ç bnŽUs3ŽÅuY“¯†¡‡Ûƒ3ƒþŒ~„µ…¨ŸÄ{ç by³œy³œnŽUuY“¯‡\
Þ†¡‡ÛŒ~„µy³œuY“¯}5šç‡\
ÞŒ~„µ‰Ç‹’…¨ŸÄy³œ}5šç…Ï•ö‡\
Þ‰Ç‹’…¨ŸÄ}5šçNš…Ï•ö‰Ç‹’…¨ŸÄNš…Ï•ö…¨ŸÄ”µ½Ù”•µ»–f³¼–f³¼šû¶²¼5£¼¾\\¦Y¼ª½VµÏ¸Ç²±n³¯¯Ñ³¯¯Ñ¶€±-¶®´ê¸0»ªáÄ”¦üÄã¦üÄã¤êË¥¡ÑÊà˜­Ë„š¬Ð˜™ÒF˜™ÒF•ŽÌ—yÀø—yÀø”µ½Ù–f³¼£¼¾\\ª½V«Æ¿ÑµÏ¸Ç³¯¯Ñ¶®´ê¦üÄã¡ÑÊà£%Ä˜­Ë„˜™ÒF—yÀø—yÀø–f³¼²¼5µÏ¸Ç¶®´ê¸0»¸0»¦üÄã£%ÄšÔ¾Ë˜­Ë„—yÀø«Æ¿ÑµÏ¸Ç¸0»šÔ¾Ë—yÀø²¼5«Æ¿Ñ¸0»£%Ä£%ÄšÔ¾Ë²¼5£¼¾\\«Æ¿Ñ£%Ä²¼5£¼¾\\£%Ä";
		-- Goretooth
		[ 17144 ] = "¿ØÂ¼ÁˆÀÄÆÎÍVÆÎÍVÅÈÓÃÒÁÃÊà¿ØÂ¼ÆÎÍVÆÎÍVÃÒÁÃÊàÅA[A<”÷<–È?±›/AØŸ;E‡Ÿ;E‡ ØR×ŸbTñŸbTñŸ\rX$[JòQ:ŒÓO¾‹ÆIy‹ÆIy‰kDÐŠCAÅA[”÷<–È?±–È?±Ÿ;E‡ŸbTñŸbTñ[J™7V¡™7V¡òQ:‹ÆIy‹ÆIyŠCAÅA[ÅA[–È?±ŸbTñŸbTñ™7V¡‹ÆIyŸbTñ‹ÆIyÅA[NwROHuYVétêVétêY³pb]\"r]\"r_pÑ`vrñ`vrñ`·xè^(|^(|_Ëƒ9\\V„÷\\V„÷W»‹NŒÓN\\ˆ7MB‚ˆO.{dO.{dNwRVétêVétê]\"r`vrñ^(|\\V„÷NŒÓNŒÓN\\ˆ7O.{dO.{dVétê`vrñ`vrñ^(|NŒÓ`vrñNŒÓO.{dg$bÊi=^«lçaåm²csh$r×j™r×j™t`oØtwörñz~tÐ}It9€kÚzxi³{gfwögfwöe¡ruhïirhïirj³lPhŒqNkûh_j³lPhïirh eµg$bÊlçaår×j™twörñz~rñz~t9€kÚzxgfwöhïirhŒqNkûh_hïirh eµh eµlçaåm²crñz~kÚzxgfwögfwöhŒqNi^uÉn;h*kûh_h eµrñz~gfwöi^uÉn;h*h eµm²crñz~i^uÉnvwüpÿjÍn;h*m²crñz~nvwür-sÉpÿjÍm²cr×j™r×j™rñz~r-sÉr×j™r-sÉpÿjÍ";
		-- Voidhunter Yar
		[ 18683 ] = "Zº¥z_¦^V«]aÿ®ù^V«]_¦c¨´eŽ¥?g_§€e«fã®¸gÕ²¯gÕ²¯jû²×k¶égé¶ygX»‘eÏÀbeÏÀbc3Ä¡`HÇ_`HÇ_aË6^—Ì}]ÅÇïY­ÇU”ÅSTÂP'ÄãNvÁÑR¾OQ[¸áR²,R²,N­æO—©ŸSg­—U‡ªX§X§W8 øYÛŸËZº¥z^V«]Z³«Úaÿ®ù_¦c¨´c¨´g_§€e«gÕ²¯k¶égé¶ygé¶yeÏÀb`HÇ_`HÇ_^—Ì}]ÅÇï]ÅÇïU”ÅSTÂSTÂNvÁÑR¾OR²,O—©ŸSg­—X§YÛŸËZº¥zZº¥zZ³«ÚW§¯\000c¯µ¡aÿ®ùc¨´c¨´e«gÕ²¯gÕ²¯gé¶y`HÇ_`HÇ_]ÅÇïSTÂSTÂR¾OR²,R²,Sg­—X§X§Zº¥zW§¯\000c¯µ¡c¨´gÕ²¯R²,X§W§¯\000b–»˜c¯µ¡gÕ²¯R²,W§¯\000U¡´b–»˜gÕ²¯`HÇ_STÂR²,U¡´_À'b–»˜`HÇ_STÂU¡´U¼º[‹À£_À'`HÇ_STÂU¼ºWÕ¾;WÕ¾;[‹À£`HÇ_WÕ¾;`HÇ_STÂ";
	};
	[ 479 ] = { -- Netherstorm
		-- Chief Engineer Lorthander
		[ 18697 ] = "@UlC¶`ªF^pF^pJ`‰KPctKPctJf?G>g†G>g†DÐnpBÊphBÊph@Ñoƒ@Ul@UlF^pKPctG>g†BÊph@UlKPctG>g†@Ult9Ñ&tFËÌv‡ÈÎv‡ÈÎ}«Ì‘±ÏH±ÏHËÕ_|6Û¿|6Û¿w´ÚŸt9Ñ&t9Ñ&v‡ÈÎ±ÏH±ÏH|6Û¿t9Ñ&•Y¬ú’ˆ G”\\”\\.ŸHŸ\\¤ÝŸ\\¤Ýí«q—š®ù—š®ù•Y¬ú”\\”\\Ÿ\\¤Ý—š®ù";
		-- Ever-Core the Punisher
		[ 18698 ] = "<k]:¦e>„cI¦jKdÉS3jÀS3jÀO.pØJ³uJ³uD¯u@Nr•@Nr•<k]>„cFRmI¦jS3jÀS3jÀJ³u@Nr•@Nr•>„c?ph FRmS3jÀ@Nr•@Nr•?ph B ldB ldFRm@Nr•;6¨:=£¢@!£SD¶¦>Iy£nK¦éK¦éJ)­ßGâ´gGâ´gJŒ·IïºûIïºû=«ÈÇ78Æ78Æ2GÀo0|·*0|·*2T§»4þ¦ö4þ¦ö7\
®\r6¡·è>p«P;6¨@!£SD¶¦>K¦éGâ´g78Æ0|·*4þ¦öAå¯i>p«P@!£S@!£SD¶¦>Gâ´g78Æ4þ¦ö6¡·èAå¯i@!£SGâ´g78Æ6¡·è9¼óB–µsAå¯iGâ´g78Æ9¼ó>V½ÒAë»<B–µsGâ´gIïºû78Æ>V½ÒAë»<Gâ´gIïºûIïºû>V½ÒAë»<—eU›˜ÛO¤šáM}¢nPß¦šOª¹QÊª¹QÊ¬ÌV°4ie°4ie¯ u÷¨*|à¨*|àž!~Ùž.s{špåž.s{ž!~Ùž!~Ù“3{boiboid2”m\\q—eU›šáM}žUP¨*|àž.s{¥%rë—âlÙšpåž!~Ùboi”m\\q—eU›—eU›žUP¢nPß°4ie¨*|à¥%rë—âlÙž!~Ùboi—eU›¢nPßª¹QÊ°4ie¥%rë©¦m¿—lgs—âlÙboi°4ie©¦m¿ªJe˜e`'—lgsboiª¹QÊ°4ieªJeœ/Y“˜e`'boiª¹QÊªJe§»Yîœ/Y“boi—eU›ª¹QÊ§»Yî¡‰VÕ¡‰VÕœ/Y“—eU›ª¹QÊ¡‰VÕ—eU›";
		-- Nuramoc
		[ 20932 ] = "T%NÙRøGüUã@oW”<]X52Zk0¤Zk0¤\\¿0¾_—6Ž_—6Ža A_BCÃ\\<Nß]íR–\\‘U¯\\‘U¯WYáU`WéU`WéT%NÙUã@oW”<]Zk0¤_—6Ž_—6Ž_BCÃ\\6D¶[6Gö\\<Nß\\‘U¯\\‘U¯U`WéUã@oUã@oW”<]_—6Ž_—6Ž\\6D¶[6Gö[6Gö\\‘U¯Uã@oUã@o_—6Ž[6Gö…zŽ‡“ŒŠŽË˜º’{§y’{­•ý­•ý°‚Ÿ°·¢{°·¢{ªd§¨	¥µ£ê¡:ˆœÓ†8šç†8šç…zŽŠŽË˜º’{­•ý°·¢{°·¢{¨	¥µ£ê¡:£ê¡:†8šçŠŽËŠŽË˜º’{°·¢{ŠŽË°·¢{£ê¡:;^Ì:ÔÈr<‹ÆšJxÊÚOÆ®eÁÃo.½ìmI´¼pv±–pv±–rˆ±:vÈº…vÈº…t÷Ç>s•É=nHÇyd•ÌZÔÍvN¸ÎËIÒt@4Ñ{@4Ñ{;^Ì<‹ÆšJxÊÚeÁÃlúÀòo.½ìpv±–vÈº…vÈº…s•É=nHÇynHÇyZÔÍvN¸ÎË@4Ñ{<‹ÆšCÊ˜lúÀòo.½ìvÈº…nHÇyN¸ÎË@4Ñ{@4Ñ{CÊ˜JxÊÚlúÀòvÈº…nHÇynHÇy@4Ñ{JxÊÚJxÊÚlúÀònHÇy";
	};
	[ 473 ] = { -- Shadowmoon Valley
		-- Ambassador Jerrikar
		[ 18695 ] = "F\
€ƒH yKPyKPyO;~Mæ“&Mæ“&Jû’ZIK‘IK‘F\
€ƒKPyKPyMæ“&IK‘pùPbqœK^uYAAuYAAwsAhyŒD›yŒD›wšQ½tgSatgSapùPbuYAAuYAAyŒD›tgSaŒ]\\ú‘W™0YÔ™0YÔ˜´_ì’f’fƒdþŒ_'Œ_'Œ]\\ú™0YÔ™0YÔ’fŒ_'y=¤‡{˜¤µ|~®ì|~®ìzî·âxe¸´xe¸´qø°4qÄ¬íqÄ¬íy=¤‡|~®ì|~®ìxe¸´qÄ¬í®B—Õ²–L¸üš^¸üš^ºd„ºÚ§ºÚ§¸õ¨º°u¥2°u¥2­I¡©¬¥¬¥®B—Õ¸üš^¸üš^ºÚ§°u¥2¸üš^°u¥2¬¥";
		-- Collidus the Warp-Watcher
		[ 18694 ] = "”¼;‹“Ã7l™x43™x43¢¢4n¬\"6f¬\"6f­58è®'H“®'H“¾ùHÀuJ	ÀuJ	ÁøV¨¿HW$™õ8K”¼;‹™x43ÀuJ	¿HW$½—LC¢38e™õ8K™x43®'H“ÀuJ	½—LCª’:r¢38e™x43®'H“½—LC«¹L¥ª’:r™x43¬\"6f¬\"6f®'H“«¹L¥¬\"6f«¹L¥ª’:r]Vjq_i³il˜il˜mŠqAuý‚£uý‚£w‰*uŠ³uŠ³o—†µl6}5a·u]«x1[‹u¡[‹u¡[…o¾]Vjq]Vjqil˜uý‚£uý‚£uŠ³l6}5a·u[‹u¡]Vjq]Vjquý‚£l6}5gÈxâa·u]Vjql6}5gÈxâ]Vjq–½‘ëÃˆŽ!¾ËŽ!¾ËŒ<¶‹à°‰‹à°‰Ž¾¯ì4µmO¦YŸv¢,ž«ª³­.µz¬¶y°¶y°«¥µ\
¢³g¢³gž}¯Ñí­iŽ!¾Ë‹à°‰4µmœPª=O¦Y¢,ž«¥8¬„ª³­.¶y°¶y°¢³gí­iŽ!¾Ë4µmØ»‘œPª=¢,ž« u¦®¥8¬„¶y°í­i–½Ž!¾ËØ»‘“¶º¦œPª= u¦®¢ª^¥8¬„í­i–½Ø»‘“¶º¦ u¦®¢ª^í­ií­i–½“¶º¦“¶º¦ u¦®í­i";
		-- Kraator
		[ 18696 ] = "e¼fÈj¬a o·cZo·cZoOnjmjme›i†e¼fÈo·cZjme¼fÈi³µRi†¬²m}¨Œm}¨Œqÿ§KrÐªWrÐªWoŠ·Îi³µRm}¨ŒrÐªWi³µR—lq œžru«yX«yX˜*€Ø–+H–+H•%y*—lq «yX–+H—lq prqv”„v”„x	 4w€(ew€(eq-%?pv”„w€(epL/m5O±kÚT•rMT•rMSñvEQbyQbyN‘v®LrGLrGL/m5T•rMT•rMQbyLrG";
	};
	[ 615 ] = { -- Shimmering Expanse
		-- Burgy Blackheart
		[ 50052 ] = "‘A´“Ã¯ì–Y³ã–Y³ã“ê·Î‘A´";
		-- Captain Florence
		[ 51071 ] = "‹‹¼žž¹k¼w¼w‘¿v‹‹¼ž";
		-- Captain Foulwind
		[ 51079 ] = "†¡­—ˆQªdŠJ­wŠJ­wˆr°o†¡­—";
		-- Poseidus
		[ 50005 ] = "ÖåÒ@”mÑ-”mÑ-–ïÔ•”×º•”×º‘Ø™Ö”mÑ-•”×ºÖc¼³M`A°Ø_i«)_i«)aA©…d2¬\"d2¬\"ef± c¼³M_i«)d2¬\"c¼³Mv»~\\wö€°u›†”u›†”r†épÄƒäpÄƒäqœ€v»~\\u›†”pÄƒäv»~\\§EkP©7i³«‹jÇ«‹jÇ¬æoO«Órä«Órä©0t2§>rþ§>rþ¦Loª§EkP§EkP«‹jÇ«Órä«Órä§>rþ§EkP";
	};
	[ 493 ] = { -- Sholazar Basin
		-- Aotona
		[ 32481 ] = "r{ˆl{À‰îy#“kÍ’þiœúd–>d–>c÷j’j’iÇƒFl€4l€4pr{ˆlr{ˆly#“p·p·kÍ’þd–>j’l€4r{ˆlr{ˆlp·d–>r{ˆld–>j’‡§‚©Š\000[°[°’°…¡øˆ“øˆ“ˆD‰­†¡†¡†¡†¡‡§‚©[°[°øˆ“†¡†¡:¢ä–+Ÿª•ã®ù•ã®ùŽË©*:¢ä„2²ˆŠî·‰#¾B‰#¾B„ãÁ¶‚&¼‰#¾B‚&¼„2²ˆu?´êsg¸0là¸ºlà¸ºl²ÀòiÛÃÖgK´ÂeŽ±Tfö­Šfö­ŠkªÚpÑ«<pÑ«<sñ®«u?´êlà¸ºiÛÃÖgK´ÂgK´Âfö­ŠpÑ«<pÑ«<u?´êlà¸ºlà¸ºgK´ÂpÑ«<";
		-- King Krush
		[ 32485 ] = "J0œC@AA\000A\000A–z…LPdQÄa4VN¸Z¬KPZ¬KP_oL^«QbXeS&Tte`N;hÛF{ÓL„|¥N;~¾N;~¾M‹ƒÃK‹àK‹àLÆ¦8J™½žJ™½žFÜ¼wI¦+I¦+G\
‹wJ0œA\000LPdQÄa4Z¬KP^«QbZçPƒK‹àJ™½žI¦+Z¬KPZçPƒXeS&K‹àI¦+J0œQÄa4Z¬KPXeS&N;~¾K‹àJ0œQÄa4XeS&N;hÛF{ÓN;~¾J0œA\000QÄa4N;hÛF{ÓJ0œA\000A\000N;hÛF{Ósor×lwvégâvégâz’g“~(m‚k³†€e¡‰Xfs‰Xfs‰m(OyrOyr{dyõyõtÐw´påsovégâ‚k³‰XfsOyrOyryõtÐw´påw´påvégâ~(m~(m‚k³Oyr~(mOyrw´pånÍB„9ËÓ…Ñ‚jÒ@¤Ì„“›ÈõOÎ}¢{Ëq¥»ÉÔ¥»ÉÔ¨^Ì5¨QÏË¨QÏË¥E×õŸßÚ’ŸßÚ’”÷ÚŸ‘Øx‹çØõ‡8ÛôƒtÖƒtÖnÍB…Ñ‚jÒ@“›Èõ–¡ÌóOÎ}¥»ÉÔ¨QÏË¨QÏËŸßÚ’‘Øx‘Øx‹çØõƒtÖƒtÖ…Ñ‚ˆQÔFjÒ@–¡ÌóOÎ}OÎ}¨QÏË‘Øx‘ØxƒtÖˆQÔFˆQÔFjÒ@OÎ}ˆQÔFOÎ}‘Øx";
		-- Loque'nahak
		[ 32517 ] = "±‰³³Ö¯N¶§¯;¶§¯;¸è³¸è¸k¸è¸k¶Ü»à³É»¥³É»¥±£¸±‰³±‰³¶§¯;¸è¸k¸è¸k³É»¥±‰³ªk¿\r­ß¾.° Æ8° Æ8«’Í¤¦Ì¸¦Ì¸¥ãÉ#ªk¿\r° Æ8¦Ì¸ªk¿\r‚×è~HÓz~;Ð~;Ð‚uÉ…„LÒñ„LÒñ…8ÖÎ‚×è~;Ð„LÒñ‚×è‘A6S“Ã3n–Ï3n–Ï3n™	6€™	;’™	;’–â?v“M?b“M?b‘[;Ÿ‘A6S‘A6S–Ï3n™	;’™	;’“M?b‘A6SX§MVXÕJJ[˜Fð[˜Fð`\000R]úT¢[˜Fð]úT¢X§MVL¥£ÃOå¤ãR©ÀR©ÀPU¯åKÀ¯AKÀ¯AIÎ¬wL¥£ÃR©ÀKÀ¯AL¥£Ã3×²37_®\\9è°‚9è°‚9†¹05Éºd5Éºd2Þ¹û3×²39è°‚5Éºd3×²3";
	};
	[ 478 ] = { -- Terokkar Forest
		-- Crippler
		[ 18689 ] = "Vš¥¡C×¢½Gf‘hGf‘hNæƒ9Y“|wY“|wfézJs€As€A}BŒ\"‚ø›’‚ø›’ƒþ­¸ª¿Øª¿Øx†Ìžm/º~X“œÙVš¥¡Gf‘hGf‘hY“|ws€As€A‚ø›’ª¿Øª¿Øm/º~q ´2^•LX“œÙGf‘hª¿Øq ´2s3­5f“^•LGf‘hª¿Øs3­5sg¤f“Gf‘hs€As€Aª¿Øsg¤l]•Lf“s€As€Asg¤q&›s€Aq&›l]•L]¿¦Ü`\rŸ\retœpetœpjÍŸ!m¦´m¦´k\"®ìeÂ²eÂ²`¯b]¿¦Ü]¿¦Üetœpm¦´m¦´eÂ²]¿¦Ü";
		-- Doomsayer Jurim
		[ 18686 ] = "]VN‘\\)Gü^.G^.G_—Næ^BTÉ]aA_\000h´^\\nß^\\nß[çnž\\qhŒ\\qhŒZra‰[çT9]VN‘^.G^BTÉ]aA^\\nß\\qhŒ\\qhŒ[çT9]VN‘]VN‘^BTÉ]aA]aA\\qhŒ]VN‘b©>íb¶;¹fÈ<~y	A}c>Ò‚Ð=¸‡191Š03:’g/¤’g/¤’°2‚‹5÷‹5÷ˆ7;¬ƒS@ª}ÙB@yDE2m¿Emm¿EmhÎCgeµ?Ueµ?Ub©>ífÈ<~‡191’g/¤‹5÷ƒS@ª}ÙB@m¿Emeµ?UfÈ<~i @‰‚Ð=¸‡191‹5÷m¿Emeµ?Ui @‰‚Ð=¸‹5÷ƒS@ªm¿Emi @‰nVB@y	A‚Ð=¸ƒS@ªm¿EmnVB@y	Ay	AƒS@ªm¿Em‹ÀStŒ/PA”¨R—XVfžZ^¡ë_iª¬o.¶~´Ö€ë¤Yc{ ½bœ«]œ«]–+YQ“US“US‹ÀSt”¨Rª¬o.´Ö€ë¨Áq[¤Yc{œ«]“US“US”¨R—XVf¥Ö`·ª¬o.¨Áq[¤Yc{“US—XVf¥Ö`·¨Áq[¤Yc{¤Yc{—XVf¡ë_i¡ë_i¥Ö`·¤Yc{";
		-- Okrek
		[ 18685 ] = "L/oùQ‰ieS&líS&líM¸sL/où{Í,‹}Š)è4/Ø4/Øo2©{Í,‹“Ö8œV>Ìš’C©š’C©’G<¿“Ö8Ž5³¼‘·¤”•¦‘ò²×“M¸0uºCŽ5³¼•¦‘ò²×‘ò²×uºCŽ5³¼";
	};
	[ 495 ] = { -- The Storm Peaks
		-- Dirkee
		[ 32500 ] = "gšƒŽhr€‰i†€oi†€oj’…Ži0‰ b”¢d9–ïb-œôb-œô^\\™	]B”L]B”L^‘aª‹’fÈ†sgšƒŽi†€oi†€oi0‰ ezŠ#b Ab”¢b-œôb-œô]B”Laª‹’fÈ†si†€oezŠ#b Ab-œôaª‹’aª‹’fÈ†sezŠ#cÐŒ~b Aaª‹’ezŠ#cÐŒ~aª‹’ifh“c×móaumóauoicþj¦ij¦ilwmÌj6p\rj6p\rgÈjºififmóauj¦iifj¦ij6p\r«}}«vE«Útg«Útg­¤tŽ¯¤{q¯¤{q­ÅÅ¬5Å¬5Å«}}«Útg«Útg¯¤{q¬5Å";
		-- Skoll
		[ 35189 ] = "uz¤Ïw¥2w´§Rw´§Ru¨¨Ît¢§yw´§Rt¢§yuz¤Ïo¾Ÿ|q45s3ž¾s3ž¾r•¢To¾Ÿ|Jõƒ•J)€ÿKáÅKáÅLÆ‚:Jõƒ•LÆ¥SLÓ¢nP\r£¢P\r£¢Nì¥µLÆ¥SF\
‚FµÅH€‰H€‰GE‚×F\
‚";
		-- Time-lost Proto Drake
		[ 32491 ] = "S9[q[…S•b-Mcb-Mcn5GÁnOM<c¢R]XrU?_ßU?_ßRÑaoLcœG8m„HètIX}\\IX}\\MÙxèV\
qÄV\
qÄ]PiKa[fÂa[fÂd÷hygÁkxgÁkxiŒpNi­|\"}‘vµyow€jJw€jJwšdZy	`vwsMnOM<n5GÁn5GÁwyGÏ€ëJá€ëJá…µN5‡ÕR@‡ÕR@‡Vé†?ZQ{djWqƒ@zûƒ@zûƒ¼~¾‚½‚½‚½‚½~.‰	xhÕ—\
d9ž¤a:£%a:£%^ù¤É\\¦Õ\\¦Õ]í¨™_ª«ô_ª«ô`¾°ÿa–·7fö«Ÿh žUjõ™ jõ™ o4•»sZ”µsZ”µwy–özŒœc|²¢Ê€U¬C}\"®!kç ëjW¬Ci*³Fi*³Ffm¸Ác¼~5²½}\"®!€U¬C€U¬C‰±NGµðGµð~‘Èü}\"Ì]}\"Ì]xÇÓFuFÕYuFÕYetÖ1aÔaÔ^ìÏË^\\ÊÍ^\\ÊÍ[ÎOUzÐ4UzÐ4M¿ÎbN±ÉxI“ÆN±ÉxM¿ÎbM¿ÎbF8ÈDDMÂ¼DMÂ¼Cø»dG§­žJ…©ÇG¦Dg›<Dg›<D3ŽBGâŽ.^Ùn[’q½S,yÎIk„‡GâŽ.D3ŽBEŽuÜC¢nHCZf®CZf®DtaœFö^¸b-McnOM<c¢Rc¢RU?_ßLcœgÁkxi­|\"iÔ…F}‘vµw€jJy	`vOO}wsMn5GÁn5GÁ€ëJá‡ÕR@‡ÕR@†?ZQ|jca{djWƒ@zû‚½‚½‚½‚½xqÄÿhÕ—\
a:£%\\¦Õ\\¦Õ_ª«ôa–·7e¯±‚fö«Ÿjõ™ sZ”µzŒœc|²¢Ê|²¢Ê}\"®!yÇ¤kç ëi*³Fc¼{dÇè~5²½€U¬C€U¬CGµð}\"Ì]UzÐ4N±ÉxUË~I“ÆM¿ÎbDMÂ¼DMÂ¼G§­žJ…©ÇDg›<GâŽ.Güš³Ik„‡D3ŽBEã}àEŽuÜCZf®Fö^¸S9[qb-Mcc¢Rc¢RLcœH­d`|}‘vµy	`vOO}n5GÁ‡ÕR@‚½‚½qÄÿlP“SsZ”µ|²¢ÊyÇ¤kç ëc¼auÀÊ{dÇè€U¬C}\"Ì]^\\ÊÍUzÐ4UË~G´Á×I“ÆDMÂ¼J…©ÇDg›<Güš³N«~žIk„‡Eã}àEã}àEŽuÜFö^¸S9[qc¢RH­d`‚©QOO}‡ÕR@sZ”µyÇ¤vÂŠwXÎå{dÇè}\"Ì]^\\ÊÍUË~ZDÉŸG§»ôG´Á×DMÂ¼J…©ÇGüš³Iü¢:L^!S9[qH­d`ƒ÷T¨‚©Q‡ÕR@sZ”µvÂŠt÷šûs÷Ð×wXÎå}\"Ì]^\\ÊÍZDÉŸ]ÅLK¯‰G§»ôDMÂ¼J…©ÇIü¢:LŸ¥`Fö^¸L^!H­d`‚ÐX	ƒ÷T¨‡ÕR@sZ”µt÷šûršs÷Ð×}\"Ì]uFÕYaÔ^\\ÊÍ]ÅLK¯‰DMÂ¼J…©ÇJ…©ÇLŸ¥`Pb¥fFö^¸H­d`GgÎ‚ÐX	‡ÕR@|jcajõ™ sZ”µršeÖÐÿs÷Ð×uFÕYaÔ]ÅL]Ù»ôNóªîK¯‰J…©ÇJ…©ÇPb¥fVÈ¤Eã}àFö^¸GgÎy	`v‚ÐX	|jcajõ™ ršm«.eÖÐÿuFÕYaÔaÔ]Ù»ô]5³¼W+ªPNóªîJ…©ÇEã}àGgÎG8m„y	`v|jcazûfYjõ™ m«.kç ëcaÏHeÖÐÿaÔW+ªPJ…©ÇVÈ¤Eã}àG8m„IX}\\y	`vzûfY{djWe¯±‚jõ™ kç ëbÌÓcaÏHaÔY³«’W+ªPVÈ¤N«~žEã}àIX}\\|y	`v{djWe¯±‚kç ëauÀÊa:ÆïbÌÓaÔ[³®Y³«’VÈ¤S,yÎN«~žIX}\\|{djW‚½‚½dg´e¯±‚auÀÊa:ÆïaÔ]5³¼^ÙnS,yÎIX}\\4€N|‚½‚½a–·7dg´auÀÊauÀÊa:Æï]5³¼^ÙnIX}\\V\
qÄ|¹ƒñ4€N‚½‚½\\¦Õa–·7auÀÊauÀÊ]5³¼[³®aNl‘^ÙnV\
qÄv§Šç|¹ƒñ‚½‚½\\¦ÕauÀÊ[³®aNl‘V\
qÄa[fÂv§Šç‚½‚½lP“S\\¦Õ[³®VÈ¤cZm¥aNl‘a[fÂp|Œjv§ŠçlP“S\\¦ÕVÈ¤]àŸve›pNcZm¥a[fÂm5ŒCp|ŒjlP“ShÕ—\
\\¦Õ]àŸve›pNa[fÂgÁkxjº‰ m5ŒClP“ShÕ—\
]àŸva4œÓfrÞe›pNgÁkxiÔ…Fjº‰ lP“SlP“ShÕ—\
a4œÓfs—frÞgÁkxlP“Sa4œÓeŽ”`fs—gÁkxiÔ…FiÔ…FlP“SeŽ”`iÔ…FeŽ”`fs—";
		-- Vyragosa
		[ 32630 ] = "S©\\[ôT9bœNbœNn¤Hen¾MàdR½]pYU¯`ƒU¯`ƒS@bL~d@G§n(IXu%IÇ~\000IÇ~\000NIyŒVzrhVzrh]¿iîaÊgfaÊgfefih1lh1liûpòj|Æ~\000wXy…o¾wïjîwïjîx	dþyxawâM¸n¾Màn¤Hen¤HewéHr[K…[K…†$NÙˆDRäˆDRä‡†W†®Zõ{Ójûƒq·ƒ¯{Ÿƒ¯{Ÿ„,bƒ,ƒaƒ,ƒa~ž‰­xr4iD—­d¨ŸHaª£Éaª£É_i¥m\\„§y\\„§y^\\©=`¬˜`¬˜a-±£b·Ûgf¬CižùkdšCkdšCo¤–_sÉ•YsÉ•Ywé—šzû}\"£n€Ä¬æ}‘®ÅlV¡jÇ¬æi™³êi™³êfÜ¹dc¼¥~¤³`}‘®Å€Ä¬æ€Ä¬æø±ñ·¶”·¶”\000ÉŸ}‘Í\000}‘Í\000y7ÓêuµÕýuµÕýeãÖÕa‰Ôµa‰Ôµ_\\Ðo^ÌËq^ÌËq[‹ÎòUêÐ×UêÐ×N.ÏO!ÊJÆ§O!ÊN.ÏN.ÏF¨ÈèD¼Ã`D¼Ã`Dg¼H®BJõªkG€¦§DÖ›àDÖ›àD¢ŽæHRŽÒ_Hn¸\\raSœzqIÛ…+HRŽÒD¢ŽæEýv€DnìCÊgRCÊgRDãb@Gf_\\bœNn¾MàdR½dR½U¯`ƒL~d@h1lj|ÆjD…é~\000wXwïjîyxa¾P wâM¸n¤Hen¤He[K…ˆDRäˆDRä†®Zõ|Ùd{Ójûƒ¯{Ÿƒ,ƒaƒ,ƒaxr4r3‘£iD—­aª£É\\„§y\\„§y`¬˜b·Ûf²&gf¬CkdšCsÉ•Yzû}\"£n}\"£n}‘®Åz6¥%lV¡i™³êc¼¥{ÓÈŒ~¤³`€Ä¬æ€Ä¬æ·¶”}‘Í\000UêÐ×O!ÊUðÌ\"JÆ§N.ÏD¼Ã`D¼Ã`H®BJõªkDÖ›àHRŽÒHl›WIÛ…+D¢ŽæFR~ƒEýv€CÊgRGf_\\S©\\bœNdR½dR½L~d@Ie€\r|¹~\000wXyxa¾P n¤HeˆDRäƒ,ƒar3‘£l¿“÷sÉ•Y}\"£nz6¥%lV¡c¼¥aåÁn{ÓÈŒ€Ä¬æ}‘Í\000^ÌËqUêÐ×UðÌ\"H$Â{JÆ§D¼Ã`JõªkDÖ›àHl›WOAIÛ…+FR~ƒFR~ƒEýv€Gf_\\S©\\dR½IeƒR@¾P ˆDRäsÉ•Yz6¥%w1ž.wÈÏ‰{ÓÈŒ}‘Í\000^ÌËqUðÌ\"Z³ÊCH¼˜H$Â{D¼Ã`JõªkHl›WJk¢ÝLq^ÅS©\\Ie„gULƒR@ˆDRäsÉ•Yw1ž.uf›ŸtgÑ{wÈÏ‰}‘Í\000^ÌËqZ³ÊC]}ÅðKx°-H¼˜D¼Ã`JõªkJk¢ÝM¦Gf_\\Lq^ÅIeƒ@X­„gULˆDRäsÉ•Yuf›Ÿruš¦tgÑ{}‘Í\000uµÕýa‰Ôµ^ÌËq]}ÅðKx°-D¼Ã`JõªkJõªkM¦PÑ¦\
Gf_\\IeG†hrƒ@X­ˆDRä|ÙdkdšCsÉ•Yruš¦fEÑ£tgÑ{uµÕýa‰Ôµ]}Åð^I¼˜Ob«’Kx°-JõªkJõªkPÑ¦\
W8¥%FR~ƒGf_\\G†hryxaƒ@X­|ÙdkdšCruš¦nÒfEÑ£uµÕýa‰Ôµa‰Ôµ^I¼˜]¥´`WšªôOb«’JõªkFR~ƒG†hrG§n(yxa|Ùd{jfýkdšCnÒlV¡cÐÏìfEÑ£a‰ÔµWšªôJõªkW8¥%FR~ƒG§n(IÇ~\000yxa{jfý{Ójûf²&kdšClV¡buÍvcÐÏìa‰ÔµZ#¬5WšªôW8¥%OAFR~ƒIÇ~\000€\r|¹yxa{Ójûf²&lV¡aåÁnaªÇ“buÍva‰Ôµ\\\"®¸Z#¬5W8¥%SœzqOAIÇ~\000€\r|¹{Ójûƒ,ƒadÖ´Âf²&aåÁnaªÇ“a‰Ôµ]¥´`_Hn¸SœzqIÇ~\000¤€ò€\r|¹ƒ,ƒab·ÛdÖ´ÂaåÁnaåÁnaªÇ“]¥´`_Hn¸IÇ~\000Vzrh}(„•¤€òƒ,ƒa\\„§yb·ÛaåÁnaåÁn]¥´`\\\"®¸a½m5_Hn¸Vzrhw‹‹}(„•ƒ,ƒa\\„§yaåÁn\\\"®¸a½m5VzrhaÊgfw‹‹ƒ,ƒal¿“÷\\„§y\\\"®¸W8¥%cÊnHa½m5aÊgfpëw‹‹l¿“÷\\„§yW8¥%^O f\
pòcÊnHaÊgfm¥Œæpël¿“÷iD—­\\„§y^O f\
pòaÊgfh1lk)ŠCm¥Œæl¿“÷iD—­^O a£wfsf\
pòh1ljD…ék)ŠCl¿“÷l¿“÷iD—­a£wfãŽ;fsh1ll¿“÷a£weý•fãŽ;h1ljD…éjD…él¿“÷eý•jD…éeý•fãŽ;";
	};
	[ 700 ] = { -- Twilight Highlands
		-- Julak-Doom
		[ 50089 ] = "~Å–\000‰#>°*“þæ—»—»’¢ \"·\"·†zc~Å~Å‰#>ŽË0°*—»\"·\"·~ÅŽË0ŽË0°*\"·";
		-- Karoma
		[ 50138 ] = "—pÑ™Dmc›wpo›wpo™ks÷—pÑˆ‰ÍŠW†8Œ‹‰áŒ‹‰áŠ…ˆ‰Í|ÙÃ›¿Ø‚Ã9‚Ã9HÇ	|ÙÃ›¤ãšç§_—©ûšÀ©ûšÀ§ržƒ¤ãšç“ê£É–fŸª™7£©™7£©–§§“ê£É‰ÍÄ‡ŒcÀuŽËÄtŽËÄtŒVÈD‰ÍÄ‡";
		-- Overlord Sunderfury
		[ 50085 ] = "’GX”•T@–ýWï–ýWï”¼[~’GX";
		-- Sambas
		[ 50159 ] = "`hŠWbë†‡eŠ~eŠ~bÞŽŠ`hŠWjÔdSmV`4oìd,oìd,mIhejÔdSr3OvtãK¦w†O}w†O}tÖS¢r3Ov|„;x~±8\
;¹;¹~«>í|„;x®ƒ@Ø°Ä=<³,@ì³,@ì°½D¼®ƒ@Ø";
		-- Tarvus the Vile
		[ 50086 ] = "€Ó›‚-Ðh„`Óz„`Óz‚TÖ¡€Ó›";
	};
	[ 720 ] = { -- Uldum
		-- Akma'hat
		[ 50063 ] = "]IšÔ_¤˜™aÄš™aÄš™a× G_±¢{_±¢{]V h]IšÔaÄš™_±¢{]IšÔ";
		-- Armagedillo
		[ 50065 ] = "qÄk]sÝh*uÜk=uÜk=sÐn5qÄk]";
		-- Cyrus the Black
		[ 50064 ] = "“3œí•E™º—EœÌ—EœÌ•SŸì“3œí¨X¯Uª=¬\"¬<¯4¬<¯4ª6²¨X¯U³•¼5µ®¸e¸¼¸¼µð¿ª³•¼5“MÕ$•2Ñ£—_Õ—_Õ•YØK“MÕ$";
		-- Madexx
		[ 50154 ] = "lC+…o\rrnèrnèuf\"y !øy !ø‰0.ž‹Ó4ä‹Ó4äŠÇ;†_A†_AAGr‚<¥r‚<¥n¸6slC+…lC+…rnèy !øy !ø‹Ó4ä†_A†_Ar‚<¥lC+…y !ø†_AlC+…";
	};
	[ 467 ] = { -- Zangarmarsh
		-- Bog Lurker
		[ 18682 ] = "cÝ¢@bä5d™ûd™ûlw”9“•“•„›˜>„µÌ‚¦+œ­~Å¬V~Å¬V\000¥s€Nž¤i^¢i«/f”¬/f”¬/cÝ¢@d™û“•„µÌ‚¦+‚¦+~Å¬V€Nž¤i^¢f”¬/d™û‚¦+€Nž¤åš…lP—i^¢d™û“•‚¦+åš…p\ršClP—d™û“•åš…~\r™~\r™p\ršCd™ûd™û“•~\r™Ò@ÆÖÁÄ‡ÛwÈÛwÈß ÑÝÌÜÙÝÌÜÙÞìÚ‹ì„Ú‹ì„Ú\"Ü(Ú³ÓêÖ$ÌíÓ2ÍìÑnËÑnËÒ@ÆÛwÈÛwÈÝÌÜÙÚ‹ì„Ö$ÌíÑnËÛwÈÛwÈÚ‹ì„Ú³ÓêÙ	Ï|Ö$ÌíÛwÈÛwÈÚ³ÓêÙ	Ï|7$9õ:74@ª2‚@ª2‚Eã3IÔ5ŽIÔ5ŽJŒ<FãI™FãI™DˆLÆ@NNi@NNi8M: EÝ:á@: EÝ8M8M6SF”7$9õ7$9õ@ª2‚IÔ5ŽIÔ5ŽFãI™@NNi@NNi: EÝ?;Gl:á@8M7$9õ@NNi?;GlBD¯<˜;~:á@7$9õIÔ5Ž@NNiBD¯@‰9	<˜;~7$9õIÔ5ŽBD¯Dñ>B@‰9	7$9õIÔ5ŽIÔ5ŽDñ>BD,:áIÔ5ŽD,:á@‰9	";
		-- Coilfang Emissary
		[ 18681 ] = "A‰yÇ?!^ùA\\VA\\VCg]æEãxïEãxïDZ{)A‰yÇA\\VEãxïA‰yÇ˜\\˜š[J¢Ý_\\¢Ý_\\§€i†¥tS¥tS£ˆv8¡&uz¡&uz °q&¢{jq Äe™Wb—“`—“`˜\\˜¢Ý_\\¥tS¡&uz¢{jq Äe—“`¢Ý_\\¢Ý_\\¥tS¢{jq¢Ý_\\¢{jq Äe´·­¶»¶§º˜Ä”º˜Ä”¸ÎÅé²9ºÚº˜Ä”²9ºÚ´·­¿ÞÇõ½ÙÅ_¿ØÂM¿ØÂMÁ©Å%¿ÞÇõO²3¢M¥€¤›¥Ï¤›¥Ï§“±ñ¦´Ž¦´ŽžØµO²3¤›¥Ï¦´ŽO²3¼cÕÂ¹õÒ¼<Ï'¼<Ï'¾UÒg¼cÕÂ";
		-- Marticar
		[ 18680 ] = "ÜŠJº}óÆu8$n(K]I+îW€+îW€,ÍLí0¤M‹0¤M‹/¸[C+qab+qab&ör@ HxÕW‰Dúà‘·à‘·K²ÜŠJÜŠJÆu8$n$n+îW€0¤M‹0¤M‹+qab HxÕW‰Dà‘·ÜŠJ$n0¤M‹ HxÕ˜€ÑW‰DÜŠJÜŠJ$n HxÕ HxÕ˜€ÑÜŠJquT÷{àK¹!L!LŽÙU9jZÀ}(Qr@[6eSZb©^„bÞf_^Ìfš^Ìfš^\\]BcaS‚!LjZÀ}(Qb©^„^ÌfšcaS‚quT÷!L}(QeSZb©^„caS‚quT÷}(QeSZcaS‚quT÷eSZ¼ÌxD°øg“°h`¾°h`¾µÂYKºJYeºJYe¿i\\V¾.aª´ðe›¿ÑuÌŠÔÌŠÔÉQŽB¼ÌxDºJYe¾.aª¹^Ò´ðe›ÌŠÔ¼ÌxDºJYe¹^Ò¶ö^ó´ðe›¼ÌxD°h`¾°h`¾ºJYe¶ö^óµa½´ðe›°h`¾°h`¾¶ö^óµa½";
	};
	[ 496 ] = { -- Zul'Drak
		-- Gondria
		[ 33776 ] = "›í—ü ËŸ\r›¬¦ï ÿgü¤µm« -t2 -t2 i¦ ÿgü®ÒÁ °ÊÁ[®¸ÍI®¸ÍI¬pÌžªÍÉ®¸ÍIªÍÉ®ÒÁ ÇR§$É©ÔÈ“´”È“´”Æš¶+ÄÂ´ÄÂ´Å2©JÇR§$È“´”ÄÂ´ÇR§$´2yk´2}—°}Š°}Š° yx´2yk¿ØdS½¤ao¿Ä^«¿Ä^«Á°ao¿ØdS";
		-- Griegen
		[ 32471 ] = "+Ú±þDg±þF€µ@ÑÇ15FÏ·3ÃÊkA|·“,·y+Ú±þ@ÑÇ13ÃÊk=ÌÃ%A|·“+Ú±þF€µF€µ@ÑÇ1=ÌÃ%F€µ=ÌÃ%A|·“8†œ~BÄŠ0E¯Š™E¯Š™F»Žß<<¡£<<¡£9# [8†œ~E¯Š™<<¡£8†œ~$ñ•Ž\" ‘$ê$ê'Â‘T$ñ•Ž•öh˜>dÉšqgÜšqgÜ˜1kJ•öh";
		-- Terror Spinner
		[ 32475 ] = "†8T9†?N¸‹N¸‹N¸‹TM†8T9Ÿì\\‹‘`4›\"\\Ÿ›\"\\ŸiYŸì\\‹µ\
:·E7ö¹^:’¹^:’¸ÛM}¶sOU¶sOU´?L’µ\
:¹^:’¶sOUµ\
:ÎBU9ÔfUmÔYY	ÔYY	Ò3\\IÎ\\\\<ÔYY	Î\\\\<ÎBU9Ã`iáÈŒjÈ³sñÈ³sñÇ1tÃMnìÈ³sñÃMnìÃ`iá¼Iª¿¥ÏÁu©ÔÁu©Ô¾Ò­¸¼Iª";
		-- Zul'drak Sentinel
		[ 32447 ] = "9^Ò;ÐIÏòIÏòI»wL’»‘L~×_;×“9^Ö+9^Ö+9^ÒIÏòIÏòL’»‘L~×_IÏòL~×_9^Ö+eã¡©eéƒieƒ¢ixŒPoßˆÎr¶Š)r¶Š)sñæt¼•öt¼•ö|¢×{]¦‡pH¶s„ÉÖK‚:Ú/vÂ¡[q–˜#p|‘aik‘œiQ¡£eã¡©eã¡©ieƒ¢ixŒPpH¶s‚:Ú/iÁ´Fik‘œeã¡©ixŒP{]¦‡pH¶siÁ´FoŽÙik‘œixŒP{]¦‡iÁ´FvÂ¡[oŽÙixŒPr¶Š)t¼•ö{]¦‡vÂ¡[p|‘aoŽÙr¶Š)t¼•övÂ¡[p|‘ar¶Š)t¼•öp|‘a";
	};
};
